### ISSUE TITLE
Java 8

### ISSUE THREAD

**Issue by adamjryan** [jsettlers/settlers-remake#104]
Would it be feasible to move to the Java 8 JDK? Some of the new features like lambdas allow much more concise code. The only potential hitch may be Android support.

**Comment by daviddawson** [comment]
There's always an alternate jvm language, for example groovy or kotlin, that has broader VM version support.                                                                                                                                                                                                                                                                                                                                        --David DawsonCEO Simplicity Itself LtdTel +447866011256Skype davidadawsondavid.dawson@simplicityitself.comhttp://www.simplicityitself.com                                                                                                                                                                                                                From: adamjryanSent: Friday, 12 June 2015 22:19To: jsettlers/settlers-remakeReply To: jsettlers/settlers-remakeSubject: [settlers-remake] Java 8 (#104)Would it be feasible to move to the Java 8 JDK? Some of the new features like lambdas allow much more concise code. The only potential hitch may be Android support.

—Reply to this email directly or view it on GitHub.

**Comment by andreas-eberle** [comment]
With JDK8, the issue really is the compatibility with Android. However, to be able to use lambda expressions (which I also would like to do), we could try to use [retrolambda](https://github.com/orfjackal/retrolambda#getting-started). I haven't worked with it, but it seems to work for Android. Maybe someone wants to test this. Probably it would be easiest if we have the gradle build environment first.

**Comment by krichter722** [comment]
reference for gradle build environment: #33

**Comment by codingberlin** [comment]
+1 Java8 for settlers.main.swing and settlers.mapcreator which does not run at android

**Comment by michaelzangl** [comment]
We switched to Java 1.8 for those projects a while ago.
