### ISSUE TITLE
a port to browser / WebGL?

### ISSUE THREAD

**Issue by Jayflux** [jsettlers/settlers-remake#113]
Hey guys, i know this isn't the most appropriate place to put this, but I couldn't find a contact email.
How feasible would it be to have a version running in the browser using WebGL? (I know its a lot of work, just wondering if its possible)

Cheers

**Comment by michaelzangl** [comment]
Hi. In theory, it would be possible. But a browser is unable to run java code, so you need to rewrite a lot of code. This is why we won't be supporting WebGL.

**Comment by Jayflux** [comment]
Thanks @michaelzangl 
Do you guys have some channel/method you communicate across? I had some questions about the development of the game.

Was also interested in making a WebGL port (which may prove too ambitious), but would need some help from you guys.

**Comment by daviddawson** [comment]
For porting to run in a web context, you would be best to investigate GWT (http://www.gwtproject.org/). 

This has plenty of decent webgl bindings and would provide the best route to porting to run on in a browser.

The settlers code is fairly well modularised, with the graphics in isolated modules (to support android).

Not everything in Java is supported in GWT, notably standard Threads are not.

Having worked with GWT quite a bit before, this would be a big job to do. It would be much easier than to fully port from Java to javascript though.
