### ISSUE TITLE
which encoding localization files?

### ISSUE THREAD

**Issue by justangel** [jsettlers/settlers-remake#12]
encoding files in resources\localization folder? what program to edit and save?

game support the choice of localization? when editing a file labels_de.properties in the game is not displayed properly, and when you create a localization file, there is no choice of which file to use

**Comment by michaelzangl** [comment]
Added multi-language support in 1d3f864055b3e68f54fbf519cc30d6440c288f10

You can add your own locale by copying the `labels_*.properties` and translating all labels. Name it `labels_<lang>.properties`. The encoding is UTF-8.

**Comment by justangel** [comment]
thank you, will have to download Eclipse, build assembly and check local

**Comment by justangel** [comment]
1 - copy/paste labels_en_US.properties and rename to labels_ru_RU.properties
2 - open labels_ru_RU.properties and replaced:
building_FORESTER    = Förster
to
building_FORESTER    = Лесник
3 - save in UTF-8 w/o BOM
4 - in game http://1drv.ms/1crdKhM the same problem text encoding

**Comment by andreas-eberle** [comment]
@justangel: 

Did you check the forester building? As the building on your image is a lumberjack. 

Furthermore, did you try Michael's branch "bugfix_12_locales"? It wasn't in the master yet, but I will merge it asap.

**Comment by michaelzangl** [comment]
You are right, the Encoding of those files was ISO-8859-1. I changed it to UTF-8

**Comment by justangel** [comment]
works perfect, thank you

**Comment by Fantu** [comment]
Thanks for this opensource project of remake of first game I buyed in the distant 1998.
Probably can be good use transifex or similar for easier and faster translations.
For now the language strings are few but if in future will be many will make a big difference.
I used transifex for example for this project and other and helped me a lot:
https://www.transifex.com/projects/p/acok/

**Comment by michaelzangl** [comment]
We might look into this in the future. Feel free to implement it, keep in mind that it should also work on Android.
