### ISSUE TITLE
I can't run this on windows 7 (hanging white screen)

### ISSUE THREAD

**Issue by Jayflux** [jsettlers/settlers-remake#121]
the JSettlers and MapCreator files look like compressed folders and they won't run.
Is there a way to run these Jar files?

If java is a prerequisite it might be worth mentioning it.
Re-installing the JRE now

Now it just hangs with a white screen
http://i.imgur.com/5C2RTrx.jpg

**Comment by andreas-eberle** [comment]
Hi Jayflux,

yes, Java is a prerequisite and yes, it should be mentioned. Thanks for the hint.

Regarding the white screen: Can you try to run JSettlers from the command line? Please follow these steps:

* Open command line (type `cmd` into the search field of the Windows start menu and hit the Enter key).
* Change the directory to the one containing the JSettlers.jar file (type `cd <PathToTheJSettlers.jar>`.
* Run JSettlers with debug printing: type `java -jar JSettlers.jar --console-output`

Can you paste the output here?

Best regards and many thanks for your report!

**Comment by Jayflux** [comment]
Seems to work when i run it from the command line
```
λ java -jar JSettlers.jar --console-output
Warning: Could not find localization/labels_en_GB.properties. Falling back to next file.
Loading Sequence number 28
```

**Comment by andreas-eberle** [comment]
Strange... can you try to start it directly (no console), again? Does it start now? Or do you have the same issue? If the issue still persists:

* What program is used to "open" the JSettlers.jar file? (Right click on the JSettlers.jar file, go to "open with" and what's written there on the top position of the list?)
* Does your PATH variable contain the path to your Java installation?

**Comment by andreas-eberle** [comment]
Hi @Jayflux: Any news here? Does it still only run from the command line?

**Comment by Jayflux** [comment]
@andreas-eberle  sorry i missed this thread.
I've moved to Windows 10 now so i don't have a windows 7 OS to test on anymore
If you want im happy to try this on windows 10 and report any issues

**Comment by andreas-eberle** [comment]
Hi @Jayflux,

it would be great if you can test it on Win10 and report any issues. I haven't upgraded my system yet, so you'd be the first one to try. Good luck! ;)

I will close this issue, as it wasn't reproducible.

Best regards!

**Comment by justangel** [comment]
on win10 all is ok for me
