### ISSUE TITLE
"Netzwerkspiel betreten" is always empty list

### ISSUE THREAD

**Issue by codingberlin** [jsettlers/settlers-remake#129]
How to reproduce on todays master:
Open with one JSettlers a network game and try to join with another JSettlers instance the game by clicking the "Netzwerkspiel beitreten" button.
The Bug is, that no open network games were shown.

What I found out so far:
In the joining client the Method receivePacket() is called with the parameter ArrayOfMatchInfosPacket packet which getMatches().length is greater or equal 1:
see: https://github.com/jsettlers/settlers-remake/blob/master/jsettlers.logic/src/jsettlers/main/MultiplayerConnector.java#L50

I don't know how the view of the Panel of the open network list works but may be this could be a hint:
I found out, that the method getJoinableMultiplayerGames() is never called.
see: https://github.com/jsettlers/settlers-remake/blob/master/jsettlers.logic/src/jsettlers/main/MultiplayerConnector.java#L61

**Comment by andreas-eberle** [comment]
I checked the server list on Android and there it works. Therefore I guess it really is a bug of the SwingUI.

**Comment by codingberlin** [comment]
Maybe I have another hint. I clicked a bit around in Git history and found this commit, wehre code was removed which dealt with the getJoinableMultiplayerGames list:
https://github.com/jsettlers/settlers-remake/commit/c3a6f6c0fa0c493309b22a7edc9091886b2e3491#diff-e1dcda68fa562910357c603fe355fca9L76

Unfortunately I crushed my eclipse and can't start it at the moment so I'm unable to test if adding back the deleted code would fix the issue.

**Comment by codingberlin** [comment]
I was able to start JSettlers in IntelliJ and was able to verify: the above shown code will show the joinable game list.
Could you please take a look at this?

**Comment by andreas-eberle** [comment]
@michaelzangl: Can you have a look at this?

**Comment by codingberlin** [comment]
Is there something else I could do to support the solution of this issue?

**Comment by andreas-eberle** [comment]
@codingberlin: Many thanks for your help. You found the correct code lines. You should really get your Eclipse working again, we need good guys like you ;)
(And sorry for the delay, I hoped Michael could fix it, but he has very little time at the moment.)
