### ISSUE TITLE
Game crashes on creating the config

### ISSUE THREAD

**Issue by andreas-eberle** [jsettlers/settlers-remake#138]
In reference to #134.

**Comment by andreas-eberle** [comment]
I was only able to reproduce this behaviour when I execute SwingManagedJSettlers in the workspace location (having the repo-folder as working dir). 

@codingberlin: Can you please try to run the game with the working directory set to `..../jsettlers.main.swing/`? Does this fix the crash after selecting the settlers folder? (Please reset the config.prp file in jsettlers.main.swing. If SwingManagedJSettlers is started correctly, this config.prp must be used. 

This could also fix the issue with the crashing multiplayer start screen (#134).

**Comment by codingberlin** [comment]
Change the working directory to settlers.main.swing/ fixed the issue.

Thx for your help!
