### ISSUE TITLE
Minimap graphical error on fullscreen

### ISSUE THREAD

**Issue by Zervox** [jsettlers/settlers-remake#14]
if you use maximize window button on windows(64bit) in my case, the minimap gets dotted looks like it is skipping a few lines in the minimap, while if I scale the window manually(by dragging the window borders) to cover the entire screen it looks ok.
(this happens in both 1.0 and 1.1 release builds on any map)

**Comment by michaelzangl** [comment]
Seems to be a regression of Bug 13 (old tracker): Map view only shows dots of the map display when the minimap size in pixel is bigger than the real map width/height. The rest is black.
