### ISSUE TITLE
Implement new multiplayer join screen / singleplayer player selection screen

### ISSUE THREAD

**Issue by andreas-eberle** [jsettlers/settlers-remake#140]
### Current Situation
* There is no player selection screen for the singleplayer games. When starting a singleplayer game, the game directly starts without a chance to select the number of players / which players should be active / which start position (i.e. player number) the player wants to have.
* When joining or opening a new multiplayer match, there is a simple but buggy and ungly join screen. However, its functions are limited.

### Target Situation
A good join screen for both, single and multiplayer games. Possibly these screens look the same, as a singleplayer game is only a multiplayer game without other human players. 

#### Important Features
* Selection of player position (playerId)
* With the new AI pull request #139, the screen should also allow to add AI players to single and multiplayer games.
* Display a preview of the selected map with the player's start locations
* Multiplayer screen needs to have a ready button for all human players
* Multiplayer screen should display a chat window with the possibility to enter messages send to all match participants. The server should already support chat messages. 
* The chat window might also be used to display error messages (e.g. "Cannot start, because not every player is ready.")
* It should be possible to give the match a name, which will be displayed in the list of open network matches.

### Way To Go
I'm open for discussion on this topic. In fact, I opened this ticket as kind of a "master ticket", which will spawn new, smaller sub-tickets containing work packages. Feel free to comment if you want to work on a specific part. E.g. @adamjryan: you did a lot of UI work already, maybe, you want to develop the screen?

Certainly, we also need to do some work on the logic side here. I can implement such parts as required.

The Android implementation is a bit further developed. It could be used as an inspiration but should also be improved in the long term.

**Comment by adamjryan** [comment]
I'd be happy to give this a go. Are you looking to reuse the original game graphics or would it be preferable to reduce the depedency on the proprietary stuff?

**Comment by andreas-eberle** [comment]
The graphics of the original are very limited and therefore the possibilities to design this would also be limited. That's why I think we should/could use new graphics. There is already support for using own graphics files. @michaelzangl: Can you give more details on this (maybe write a wiki page?). Maybe you can "draw a picture" to give a first idea of the result and have a basis for discussions?

**Comment by andreas-eberle** [comment]
I just had a discussion with @michaelzangl. We came to the conclusion, that we should not continue building the menu with our own OpenGL-based UI elements. Instead, we plan to create the main menu as SwingUI and skin that. @michaelzangl will implement a simple SwingUI version of the main menu.

**Comment by adamjryan** [comment]
It might be an idea to consider JavaFX then as it has quite a few enhancements on Swing as well as FXML for a nicer seperation between the view and the controllers.

**Comment by andreas-eberle** [comment]
@adamjryan: Do you have experience with FXML and JavaFX? From what I just read, it is part of Java8? However, as the SwingUI is seperated from the Android code, we could use Java8 here. 

As we also plan to rebuild the complete main menu on "not-Android" devices, we should consider using these newer technologies for that as well. Would you also be interested in implementing issue #141?

**Comment by adamjryan** [comment]
Yes, I'll take that one up. I've made an application in JavaFX and know how the FXML works so I can put up something.

**Comment by codingberlin** [comment]
+1

I really looking forward to this because I often have to choose different PlayerSettings while I'm working on the different AIs.

**Comment by andreas-eberle** [comment]
Fixed with #268.
