### ISSUE TITLE
Change Swing Main Menu to a JavaFX UI

### ISSUE THREAD

**Issue by andreas-eberle** [jsettlers/settlers-remake#141]
Currently the main menu on Windows, Linux and Mac is implemented with self-made OpenGL-based UI components. We should change the main menu to a real SwingUI to be able to use the normal UI controls. This will reduce the amount of work required for implementing this controls ourselves and the number of possible bugs / flaws.

This is a prereqisite of #140.

**Comment by andreas-eberle** [comment]
As discussed with @adamjryan and @michaelzangl, @adamjryan will take over this task and implement a UI with JavaFX.

**Comment by andreas-eberle** [comment]
@adamjryan: Is there any progress? Don't feel pressured, I'm just curious ;) Maybe you can create a PullRequest as soon as you have something, so we can follow your work easily.

**Comment by adamjryan** [comment]
I'm hoping to get a chance tomorrow, I've got a few things on the go atm.

**Comment by codingberlin** [comment]
+1

I really looking forward to this, because it is a prerequisite of the feature #140 I really want to use :)
Furthermore this is the basement to handle build a new map-chooser menu for the tons of original maps which becomes available with #238.

**Comment by andreas-eberle** [comment]
Hi @adamjryan: Did you have a chance to look at this, yet?

**Comment by andreas-eberle** [comment]
As discussed in #264, we will not switch to a JavaFX UI as it has to many drawbacks. However, we will rebuild the main menu. I created issue #268 for that.
