### ISSUE TITLE
Terrain Frustum problem.

### ISSUE THREAD

**Issue by Zervox** [jsettlers/settlers-remake#15]
I notice terrain becomes black at the bottom part of the screen when moving over mountains, this does not happen on flat ground level terrain, it looks like frustum culling problem to me, as if the tiles are outside frustum while they should be inside.
(this happens in both 1.0 and 1.1 release builds on any map)

**Comment by michaelzangl** [comment]
Bug 85 in old tracker.

**Comment by andreas-eberle** [comment]
This was implemented in e8c8c96813910b44e1828adcd781a455192f29f0.
