### ISSUE TITLE
Implement calculation of mine productivity

### ISSUE THREAD

**Issue by andreas-eberle** [jsettlers/settlers-remake#151]
As of cb18427708f6ba3344463a2202b5287da2e872d2, the UI can now display the productivity of mines. This must now be calculated in the game logic and also be used for the mining action.

**Comment by andreas-eberle** [comment]
@codingberlin: Do you know / are you able to guess how the productivity is calculated in the original game exactly? Do you know further rules for the mines (e.g. how often the mine will work at the start before getting any food)?

**Comment by codingberlin** [comment]
I tested it with the original settlers3 some minutes ago with a coal 100% Mine:

- after I build it without food, I got 10 coal baskets
- with a fish (not the corresponding food for coal) I got 2 baskets of coal
- with a bread (the corresponding food for coal) I got 10 baskets of coal

The mine showed 100% a long time. Even I got 339 baskets of coal out of it.
With 87% I had 531 baskets of coal. Then the % increased, decreased, increased, decreased and so on.
So my guess is, that the last x tries to get coal goes into the calculation of the %.

After 957 baskets of coal the mine was empty.

The corresponding food for mines are:
coal - bread
iron ore - meat
gold - fish

**Comment by codingberlin** [comment]
I thought about why the mine productivity is decreasing and increasing in the original settlers 3.

If the mine would be build over x stacks of coal and all stacks are full and if the miner would take a basket of coal from the first stack, than from the second and so on ... then the mine would have 100% all the time and from the one to the next moment it would decrease to 0%.
So this behavior we can exclude.

So my guess how it works is:
The mine has x stacks of coal. The stacks are visited by random order. The random order leads to different stack amounts. Until all stacks have at least 1 coal the mine has 100%. When the first stack is empty and randomly visited by the miner, the productivity of the mine decrease. If then the empty stack is not randomly visited for some time, the productivity of the mine increases.

**Comment by andreas-eberle** [comment]
This seems like a good explanation. Now there is the question if we want to calculate the productivity like in the original, or if we want to calculate it correctly (remain/max)?

**Comment by codingberlin** [comment]
I think there are two KPIs:
amount -> tells me, how long the mine will work
frequency -> tells me, how many smiths the mine can supply

As I played the original settlers I had the following rules of thumb in mind:
- 1 farm can supply 3 mines (iron, coal, coal)
- 1 mine can supply 2 buildings
This rules of thumb looks at the frequency, which means if I just can build a 50% mine in my rock (e.g. at alien.map an iron mine at the side of the mountain) I just can supply one building and I have to build another mine for the next building which means that I have to gather more food first.

From the amount (remain/max) I would not be able to extrapolate how many farms and smiths I can build with this mine(s).

What's your opinion?

**Comment by andreas-eberle** [comment]
Wow, thanks for this detailed information!

I will then supply these two values (amount and frequency).
