### ISSUE TITLE
Change to maven as build system

### ISSUE THREAD

**Issue by krichter722** [jsettlers/settlers-remake#155]
Although the build process involves a lot of custom build scripts run by `ant` it'd pay off to migrate to maven sooner or later.

I started this migration without knowing much what I was doing, but at least noticed some strange locations regarding unit and integration tests (e.g. tests which require functionality of the swing main project, but were placed in the swing project). maven's design avoids such issues and enforces proper package management.

**Comment by andreas-eberle** [comment]
First of all: Yes, the current "build system" needs to be reworked.

Actually there is already a ticket for switching to a gradle build system #33 and a pull request #51 for this has already been started but stalled for a while. I don't know how well Maven works with the Android part of the project. Do you have any experience with this?Usually Android uses Gradle.

What I like about the current build system is that starting the game (during development) does not require a long compilation time (at least with Eclipse), as only a few resources are generated and need to be compiled again. I think this is a very important "feature" as a long compiling time makes development much harder. I don't know if there are ways to achieve this with maven, I only developed Java EE Webservices with it and there, the compilation times was pretty bad.

**Comment by krichter722** [comment]
> Actually there is already a ticket for switching to a gradle build system #33 and a pull request #51 for this has already been started but stalled for a while. I don't know how well Maven works with the Android part of the project. Do you have any experience with this?Usually Android uses Gradle.

Then definitely Gradle as the difference in capabilities of gradle and maven is not that big.

> What I like about the current build system is that starting the game (during development) does not require a long compilation time (at least with Eclipse), as only a few resources are generated and need to be compiled again. I think this is a very important "feature" as a long compiling time makes development much harder. I don't know if there are ways to achieve this with maven, I only developed Java EE Webservices with it and there, the compilation times was pretty bad.

I don't know about that. Yet, the feature to let the build tool (maven or gradle) manage declared dependencies it worth its weight in gold.

**Comment by daviddawson** [comment]
I'd ba happy to lend a hand getting it finished, I'm a little pressured on time to fully do it myself now, sorry!

The only real piece missing is the android build,adding a module that permits an android integration, use with android studio etc.

The rest should all work, after bringing up to date with master.

**Comment by michaelzangl** [comment]
Currently we only have one dependency for Swing:
-> JOGL.

For Android, we don't have any external dependencies.

I'd rather not make the build system too complicated. Maven is great when you use a lot of dependencies, but I do not see the need for it at the moment. We focus on eclipse for development, that way, we do not need much compatibility - just enough to let travis tests run and allow compiling from the command line.

**Comment by andreas-eberle** [comment]
It seams that we agree on using Gradle as build system. Therefore I'm closing this ticket in favour of #33.
@krichter722: Maybe you can assist the Gradle integration?

**Comment by krichter722** [comment]
> It seams that we agree on using Gradle as build system.

In case we don't (@michaelzangl seems to be at least indifferent) we should discuss this in #33.

> @krichter722: Maybe you can assist the Gradle integration?

Will do.
