### ISSUE TITLE
Add licence information

### ISSUE THREAD

**Issue by krichter722** [jsettlers/settlers-remake#156]
by mentioning them in README and by adding a COPYING file in the source root.

Information about the relation to the license of the proprietary demo binary dependency would be appreciated (compatibility, plans to replace resources from it one day).

**Comment by andreas-eberle** [comment]
What should be in the "COPYING" file? Did you mean a LICENSE.txt file with the MIT license text?

**Comment by krichter722** [comment]
> Did you mean a LICENSE.txt file with the MIT license text?

Yes, the GNU guys call their license files usually COPYING as they're struggeling with the word license - makes sense, but LICENSE is perfectly fine as well.

I was just confused about how it works that the resources can be taken from the proprietary demo and used and thought it'd be nice to have that explained in README or a file that addresses devs (DEVELOPERS or HACKING). Non-dev users might be concerned about that as well (might wonder "Is it illegal to use settlers-remake?"), so putting it in README is preferable.

**Comment by krichter722** [comment]
If you do `git commit --amend` you could close the issue with the commit message (write `fix #156`).

**Comment by andreas-eberle** [comment]
I know, but I also wanted to add a comment to the readme ;)

**Comment by michaelzangl** [comment]
I think the license is mentioned in enough places for everyone to see it.
