### ISSUE TITLE
Add hint about mailing list to README

### ISSUE THREAD

**Issue by krichter722** [jsettlers/settlers-remake#158]
Both the information that there's a list and there's none (not yet or on purpose) and how to discuss development otherwise if there's none are useful information for `README`.

**Comment by andreas-eberle** [comment]
I already thought about introducing a mailing list. Does anybody have experices with mailing list providers and can recommend a provdier? 

@all (especially @michaelzangl, @codingberlin): Do you think a mailing list is a good idea for discussing technical topics? Of course the ticket system would still be the way to coordinate and log "work packages".

**Comment by krichter722** [comment]
We could try [gitter](https://gitter.im/) which has good integration with github.com. It's a browser-based chat application. If you make it a rule to keep conversations public and clean (no "Thank you", "lol, me too" bs) it shouldn't be too different from a mailing list.

**Comment by codingberlin** [comment]
I have no experience with mailing lists. The alternative Lobby for Settlers3 we implemented backed by a Forum where we kept the progress and discussions. This worked quite well.
But maybe a mailing list works, too.

**Comment by andreas-eberle** [comment]
I'm closing this because we will continue discussing tickets and PRs here on Github and additionally have the Discord for a more direct communication (instead of a mailing list). I will also add a note on the discord in the readme.
