### ISSUE TITLE
Feature Level Up Soldiers

### ISSUE THREAD

**Issue by codingberlin** [jsettlers/settlers-remake#161]
It should be possible to level up the soldiers.

I startet to implement this in the branch feature_level_up_soldiers and request for help now:
Can someone implement the GUI interface or explain to me how to implement GUI interface?

with:
```
ManaInformation.isBowmenUpgradePossible()
ManaInformation.isSwordsmenUpgradePossible()
ManaInformation.isPikemenUpgradePossible()
```
... the GUI can decide if the level up buttons are en- or disabled

And if a button is pressed you can schedule an ```UpgradeSoldiersGuiTask()``` with ```BOWMEN_L1```, ```SWORDSMAN_L1``` or ```PIKEMAN_L1``` to upgrade the soldiers.

**Comment by codingberlin** [comment]
I have another question:
What do I have to do to store the ManaInformation in savegames?
I think the players won't like it to loose their Level3 after loading a savegame :)

**Comment by andreas-eberle** [comment]
The ManaInformation needs to be attached to the Player object (as it depends on the player). If that is done and your class implements the Serializeable interface, the information will be stored and loaded automatically. (Currently we use Java Object Serialization for saving the game).

**Comment by codingberlin** [comment]
Ah this means that everything is prepared for save games already:
https://github.com/jsettlers/settlers-remake/blob/feature_level_up_soldiers/jsettlers.logic/src/jsettlers/logic/player/Player.java

**Comment by andreas-eberle** [comment]
Yes, that looks good.

**Comment by codingberlin** [comment]
@michaelzangl regarding your comment at 7565d33 
> - A feedback mechanism that tells us the things the GUI should display (discuss with @andreas-eberle). We could probably attach this to the statistics.

I talked with @andreas-eberle. The GUI should look like in the original game

The only thing which is missing is the GUI now.
I would appreciate help with this. Ideally I would understand how to create GUI to be able to do this in future. But it is ok for me, too, when you implement the GUI and I go through the commits to understand it.
