### ISSUE TITLE
adapt fight system to original settlers and add KK (combat strength)

### ISSUE THREAD

**Issue by codingberlin** [jsettlers/settlers-remake#162]
Soldiers have a combat strengh which increases by gold and is at minimum 100% within the own land.
Some years ago I made a test with the original game: https://tips.siedler3.net/page.php?lan=de&article=gold (german)

The soldiers have different hit points, strength and range.
Important is the range of 2 of pikemen. They are good in tight fights because they can attack from the second line but they are weak in wide areas due to their hitpoints and strength.

# strength
|soldier|hitpoints|strength|range|hit every x seconds|
|---------|-----------|-----------|-------|-------|
|swordsman lv1|100|10|1|0.7|
|swordsman lv2|120|14|1|0.7|
|swordsman lv3|150|20|1|0.7|
|pikeman lv1|200|4|1-2|0.7|
|pikeman lv2|240|5|1-2|0.7|
|pikeman lv3|300|6|1-2|0.7|
|bowman lv1|100|5|5 - 15 (25 from tower)|1.4|
|bowman lv2|120|6|5 - 15 (25 from tower)|1.4|
|bowman lv3|150|7|5 - 15 (25 from tower)|1.4|
|priest|80||
|pioneer|20||
|geologist|20||
|thief|20||
The list is based of: https://www.siedler3.net/cb3/verhaeltnis-von-kampfkraft-zu-level-der-soldatenp26794/#real26794 and http://www.siedlercommunity.de/c-Siedler-3-Hitpoints-s81.html and the measurements in the comments below.

# speed
|movable|speed [seconds per 100 tiles]|
|---------|-----------|
|priest|70|
|pioneer|60|
|geologist|60|
|bearer|60|
|thief|60|
|bowman|60|
|pikeman|50|
|swordsman|45|

**Comment by IridiumOxide** [comment]
They also have different movement and attack speed. I've seen a different table: http://www.siedlercommunity.de/c-Siedler-3-Hitpoints-s81.html , but I don't know if the values are right, as hitpoints and strength seem to be wrong in this one. That site also states that Amazon soldiers have 20% less strength.

**Comment by codingberlin** [comment]
I found that table, too.
It is correct, that the Amazon soldiers have 80% hit points. I left that out because currently the remake has only Roman.
I choose the table mentioned above because it is out of a manual and fits better my experience with the game.

**Comment by codingberlin** [comment]
Regarding speed and attack frequency: @andreas-eberle is it possible to influence that with the current code?

**Comment by andreas-eberle** [comment]
The attack frequency and walking speed can be influenced. The current code uses fixed constants for all movables. This can easily be changed. @codingberlin: Can you supply the walking speeds of various movable types (in #164)  and add the attack duration of the soldier types in your table?

**Comment by andreas-eberle** [comment]
One more thing: What is the minimum range of bowmen?

**Comment by codingberlin** [comment]
I made a test with the original settlers:
![reichweite](https://cloud.githubusercontent.com/assets/6422616/10004457/0abedd46-60b2-11e5-81ec-91a50274fbd5.png)

I counted the tiles in the editor and it turned out, that the bowman was not able to shoot with range 4, but with 5 to 15.   ... The table above says 12 maximum range. ... so I do another test with a tower

**Comment by codingberlin** [comment]
To count the range with a tower was more difficult but it is something between:
max: 23-25
min: 5

**Comment by codingberlin** [comment]
I measured the speed of the following movables and updated the table above:
![speed](https://cloud.githubusercontent.com/assets/6422616/10011626/7c4839f8-60fd-11e5-844b-a95318717f95.png)

I worked with 200 tiles and measured the seconds the movables need, to reach their destination.

**Comment by andreas-eberle** [comment]
Wow, awesome! Thanks for these values! I will implement the movable speeds and attack frequencies.

**Comment by codingberlin** [comment]
I need some help with implementing the combat strength
I created the new feature_combat_strength branch and have 90% finished now but I have a problem:

Here:
https://github.com/jsettlers/settlers-remake/blob/feature_combat_strength/jsettlers.logic/src/jsettlers/logic/player/CombatStrengthInformation.java#L46
I try to get all player's partitions to get their amount of gold. Unfortunately I got hundreds of partitions instead of one (created by using pioneers to get the gold mountain to build the gold mine at mountain lake)
When I start the game I already get 2 partitions.

Summarized I'm confused how the partitions work. Could someone help me implementing the ```getPartitionsOfPlayerId```method or another way how I get the amount of all the gold in all players partitions?

Thx a lot!

**Comment by michaelzangl** [comment]
Mind that we want this method to be fast, thus not contain any O(n) loops (or even worse loops).

A nice way would be to change the OffersList. Create a new class for the PlayerStatistics that holds statistics for the whole player. The OffersList (in PartitionManager, but don't bring player relevant stuff in there. e.g. create a OffersList#trackToPlayerStatistics(...)) can then inform the statistics of any updates on it's end. That way, we can track the global amount of any items for all players. This includes the number of produced gold.

**Comment by andreas-eberle** [comment]
I suggest keeping an always up-to-date count of a player's global amount of every material. This might also be used in the UI and presented (e.g. in a tool-tip) to the user as it might be useful in some situations. I will have a look at the code and add the global material counting for each player.

**Comment by andreas-eberle** [comment]
I implemented the counting for a player's materials in the branch and refactored the code that the partitions grid is not given to the Player object. Therefore we can now access the global material counts of players in constant time.

**Comment by codingberlin** [comment]
I figured out the hitpoints of priest, theft, geologist and pioneer and add them to the table above.

**Comment by krichter722** [comment]
I know, I already requested info in #156, but I might point you attention to an issue at this point as well (serves as a good example why clarification in #156 is necessary): Don't you think that the calibration of game balancing is intellectual property and needs to be figured out by trial and error (and documented as such) and/or in automated experiments exclusively based on the achievements of this open source project?

**Comment by andreas-eberle** [comment]
I don't think it is an issue to determine some properties from the original game at the moment. Especially, as we will have to tweak them ourselves for our game. Of course we want to build a remake, but some values need to be adjusted (e.g. walking speed is way to slow for our game). And these adjustments will cause other adjustments. 

However, for the beginning these values are very useful to make the game working.

**Comment by codingberlin** [comment]
The only thing which is missing for this issue is the "hit every x seconds" implementation.
As we discussed to rebalance the game at a later point it would be the same if we reduce the strength of the bowmen or if we slow the "hit every x seconds" down. So I come to the conclusion that this does not need to be implemented and this issue can be closed.
