### ISSUE TITLE
Implement differing walking speeds for different movable types

### ISSUE THREAD

**Issue by andreas-eberle** [jsettlers/settlers-remake#164]
Currently all movables have the same walking speed. In the original game, the walking speed differs between different movable types. E.g. the swordsmen are faster than bowmen. 

@codingberlin: Do you have information on the step durations of the different movable types?

**Comment by codingberlin** [comment]
Unfortunately not. @IridiumOxide mentioned a table here: http://www.siedlercommunity.de/c-Siedler-3-Hitpoints-s81.html ... where you can find the speeds "1, 0.7 and 0.4" for the different movableTypes.
I read that speeds some years ago somewhere, too. But I don't know what they mean: Maybe 1 is like for all other movables and 0.7 is 70% of speed of the other movables.

I'll do a test with the original game soon to figure that out.

**Comment by michaelzangl** [comment]
We should also consider adding a way to slow the faster movables down to the speed of the slowest in the selected group dynamically. E.g. by shift-clicking. Of cause, having formations would be even better ;-)

**Comment by andreas-eberle** [comment]
### walking speeds as determined by @codingberlin in #162
|movable|speed [seconds per 100 tiles]|
|---------|-----------|
|priest|70|
|pioneer|60|
|geologist|60|
|bearer|60|
|thief|60|
|bowman|60|
|pikeman|50|
|swordsman|45|
