### ISSUE TITLE
Error running/debugging in Eclipse

### ISSUE THREAD

**Issue by stumpdk** [jsettlers/settlers-remake#166]
This is question, not a bug:
When I run the jsettlers.main.swing project I get this error:

Error: Could not find or load main class jsettlers.main.swing.SwingManagedJSettlers

I've build all project (ctrl + b).
I right click the jsettlers.main.swing project and click Run as Java Application. After that I select the SwingManagedJSettlers - jsettlers.main.swing item.

My run configuration (default from source) is this:
Project: jsettlers.main.swing
Main class: jsettlers.main.swing.SwingManagedJSettlers

IDE: Eclipse for Java Developers v. 4.5.0 clean installation.

**Comment by andreas-eberle** [comment]
What is the working directory you're using? 
I usually don't select the project and then run (as you described). Instead, I select the SwingManagedJSettlers class and Run it directly. Maybe this helps?

Another idea: Do you have the project set to "build automatically"? You can set this in the top navigation bar under "Project" => "Build Automatically".

Did anything of this help?

**Comment by stumpdk** [comment]
Hi Andreas
Thank you for your reply.
I've tried running the SwingManagedJSettlers class directly (Right click, Run as) as well as by using ctrl + f11. The project settings already has build automatically set.

If you clone the project into a brand new workspace in Eclipse Mars, without any plugins, this works for you?

**Comment by andreas-eberle** [comment]
I just realised that I'm using Eclipse Luna. I will check it with Mars.

**Comment by stumpdk** [comment]
Okay. I'm looking forward to hear if I'm just totally wrong. :)

**Comment by andreas-eberle** [comment]
I just downloaded Eclipse Mars and a fresh clone of the repository and it worked.

Some more questions and ideas:
* Does Eclipse display any errors? 
* Did you run the `build.ant` file in the project's top-level folder before trying to run the game?
* How did you import the projects into your workspace? Did you create a new and clean workspace for the project?

Best regards

**Comment by stumpdk** [comment]
I got it working. I forgot a very important thing. 
The problem was that I did not have the Java JDK. 

Based on your answer I got it to work by doing this:
I imported the project
I ran the built.ant file in the SwingManagedJSettlers project.
This gave me a compiler error (I needed the Java JDK)
I installed the Java SDK
I added the JAVA_HOME as a Windows path

And the game compiles and runs.

Thanks alot for your help!
Do you want me to update the Windows instructions in the readme?

**Comment by andreas-eberle** [comment]
Glad to hear that it works now. Feel free to send me a PullRequest with the updated Readme!

**Comment by stumpdk** [comment]
[pull request #176](https://github.com/jsettlers/settlers-remake/pull/176) has an updated readme.
