### ISSUE TITLE
Implement market logic

### ISSUE THREAD

**Issue by michaelzangl** [jsettlers/settlers-remake#187]
The market logic contains
- The list of materials that should be brought to the market (+ UI interface)
- The path that the donkeys should walk (+ UI interface)
- Adding the request stacks to the map (we might need a new multi-request type here)

**Comment by michaelzangl** [comment]
Waypoint actions: def0af77720a0fb9756b0b9519178d0dc4d5efdf

**Comment by andreas-eberle** [comment]
Implemented a while ago.
