### ISSUE TITLE
Add donkey movable strategy

### ISSUE THREAD

**Issue by michaelzangl** [jsettlers/settlers-remake#188]
We already have a special movable type (donkey).

We need to implement it and make it addable to the map. This includes
* Check the right images
* Allow the donkey to carry materials (pick them up)
* Allow it to drop materials
* From a list of available market stacks, select one, go there, get the material and then walk the path that was specified for that market. Requires #187

The implementation can reuse lots of the bearer logic.

**Comment by codingberlin** [comment]
The donkey is attackable when it is carrying material: with the first hit, it drops the material and is not attackable anknote.
The donkey can't die.
The donkey can take only materials from the market.

**Comment by andreas-eberle** [comment]
Closing this, as it was implemented a while ago.
