### ISSUE TITLE
Implement donkey farm

### ISSUE THREAD

**Issue by michaelzangl** [jsettlers/settlers-remake#189]
The building is already added in e2622de4bbef6dc7e72f3401404f052d291fe012.

We need to
* ~~Set the right amount of stone/planks~~
* Add the (growing) donkey map object
* Add the worker jobs to the xml file
* Make it produce donkeys (requires the donkey movable) #188

**Comment by krichter722** [comment]
Why is the issue not closed automatically/the `Fixes #189` in the commit message not recognized?

**Comment by andreas-eberle** [comment]
The fixes message closes the ticket, as soon as the commit is in the master. As this implementation is only in a branch at the moment, the fix is not "finished" yet.

**Comment by krichter722** [comment]
I see...
