### ISSUE TITLE
Backslash in Properties file needs to be escaped.

### ISSUE THREAD

**Issue by namelessjames** [jsettlers/settlers-remake#19]
JSettlers is not starting on Windows 8.1 Pro 64-bit (6.3, Build 9600). No logs created.

1. Unpacked and installed JSettlers correctly.
2. Installed S3-Version is from GoG.com (has both SND and GFX folders)
3. Edited Settlers 3 Installation Path in config.prp (also tried encapsulating the path with " )

JRE-Version: 8.0_40 (both 64 and 32-bit)

-
Also tried to run it from the command prompt (admin and non-admin). Exception when running from command prompt:
Exception in thread "main" java.io.FileNotFoundException: config.prp (The system
 cannot find the file specified)

**Comment by andreas-eberle** [comment]
Hi @namelessjames,

thanks for your report! Can you answer the following questions?

- when running the jar from the command prompt
  - what where your exact arguments / what did you enter? 
  - Please run the game from the command line with ```java -jar JSettlers.jar --console-output``` an post the complete result.
- Can you also attach your config.prp file or post it in the comment? (Just to make sure there is nothing missing.)
- Did you try to start the game with both JREs(64bit and 32bit)? Or do you just have them installed in parallel. If so, please try to explicitly start the game with the 64bit JRE. 

Many thanks for your help!

**Comment by namelessjames** [comment]
Hi @andreas-eberle 

thanks for your reply :)

# Answering your questions

> what where your exact arguments / what did you enter? 
```java -jar JSettlers.jar```

> Please run the game from the command line with java -jar JSettlers.jar --console-output an post the complete result.

Please see below


> Can you also attach your config.prp file or post it in the comment? (Just to make sure there is nothing missing.)

Yeah sure: ```#This properties are used for development
#Specifies the folder where the resources can be found. NOTE: The path needs to end with a slash ( / )
resources-folder=resources/
#Folder containing the folders of the graphics and the sound files. If you want to specify multiple possible folders, use a ";" character for separation.
settlers-folder=C:\Program Files (x86)\The Settlers 3 - Ultimate Collection```

> Did you try to start the game with both JREs(64bit and 32bit)? Or do you just have them installed in parallel. If so, please try to explicitly start the game with the 64bit JRE. 

Both versions are installed. There seems to be a problem with the 64-bit Path Constant or the registration of the 64-bit-version of JRE though - see 3. and 4. of the tests below. Do you have a clue for me here? ```java -version```-result: ```java version "1.8.0_25"
Java(TM) SE Runtime Environment (build 1.8.0_25-b18)
Java HotSpot(TM) Client VM (build 25.25-b02, mixed mode, sharing)```


# Running four tests:
1. cmd non-admin java 32-bit
2. cmd admin java 32-bit
3. cmd non-admin java 64-bit
4. cmd admin java 64-bit

## Result for 1.
**used command:** ```java -jar -d32 JSettlers.jar --console-output```
**outcome:**
```Exception in thread "main" SettlersDirectoryException [expectedSnds=[C:Program Files (x86)The Settlers 3 - Ultimate Collection/SND], expectedGfxs=[C:Program Files (x86)The Settlers 3 - Ultimate Collection/GFX], badVersion=true]
        at jsettlers.graphics.swing.resources.SwingResourceLoader.testConfig(SwingResourceLoader.java:67)
        at jsettlers.graphics.swing.resources.SwingResourceLoader.setupSwingResources(SwingResourceLoader.java:25)
        at jsettlers.graphics.swing.resources.SwingResourceLoader.setupSwingResourcesByConfigFile(SwingResourceLoader.java:21)
        at jsettlers.main.swing.SwingManagedJSettlers.setupResourceManagers(SwingManagedJSettlers.java:73)
        at jsettlers.main.swing.SwingManagedJSettlers.main(SwingManagedJSettlers.java:53)```

## Result for 2.
**used command:** ```java -jar -d32 JSettlers.jar --console-output```
**outcome:** Same as Result for 1

## Result for 3.
**used command:** ```java -jar -d64 JSettlers.jar --console-output```
**outcome:** ```Error: This Java instance does not support a 64-bit JVM.
Please install the desired version.```

## Result for 4.
**used command:** ```java -jar -d64 JSettlers.jar --console-output```
**outcome** Same as Result for 3

**Comment by michaelzangl** [comment]
Hi. The backslash in properties files needs to be escaped. Try this:

settlers-folder=C:\\Program Files (x86)\\The Settlers 3 - Ultimate Collectio

I still believe this is a bug, we should at leas warn about this issue.

**Comment by namelessjames** [comment]
hi @michaelzangl 

that works just fine! Thank you. :+1:

**Comment by justangel** [comment]
windows 8.1 x64 jSettlers starting fine for me

C:\WINDOWS\system32>java -version
java version "1.7.0_60"
Java(TM) SE Runtime Environment (build 1.7.0_60-b19)
Java HotSpot(TM) 64-Bit Server VM (build 24.60-b09, mixed mode)

but DedicatedJSettlersServer_v0.1-alpha.jar and MapCreator.jar after starting immediately closed

**Comment by Zervox** [comment]
"C:\\Program Files (x86)\\The Settlers 3 - Ultimate Collectio"
I found it easier to just do
C:/Program Files (x86)/The Settlers 3 - Ultimate Collection/"

also I've the same close with server and MapCreator.

**Comment by andreas-eberle** [comment]
In my opinion, the best solution for this issue is to focus on #8. This will solve this issue (as users don't have to edit the file) and will increase user comfort.

**Comment by andreas-eberle** [comment]
I close this, as #8 has been implemented.
