### ISSUE TITLE
Make settlers move to closest territory instead of killing them when territory is lost

### ISSUE THREAD

**Issue by krichter722** [jsettlers/settlers-remake#200]
Currently all settlers die which were standing or moving on now lost territory which is pretty hard on the game balancing given the fact that

  * > 500 settlers easily find place in the space covered by one tower
  * builders and graders need to be recreated for the cost of 1 piece of coal and iron for their tools.
  * attacks in the not so well guarded back of territory far from the border where houses are preferably build and thus free settlers group massively have extreme impact.

experienced with v0.1.3-alpha-329-g925ee6f

**Comment by andreas-eberle** [comment]
Settlers are actually already walking back to there territory. However the distance in which they find their way back is quite small at the moment.

@codingberlin: Do you have a feeling how large this distance should be? Probably larger than one tower radius or so.

**Comment by krichter722** [comment]
How about 1.5 ranges of the largest territory covering building (castle)?

**Comment by michaelzangl** [comment]
Issue was solved a while ago...
