### ISSUE TITLE
Tower door is attacked for ever

### ISSUE THREAD

**Issue by krichter722** [jsettlers/settlers-remake#203]
Apparently it can happen that tower doors are attacked for ever. Warriors are moving away and approaching the door in an endless loop. See [this video](https://richtercloud.de:447/owncloud/index.php/s/hAN9qllDl0b6LLC) I created from AI player (same can happen for human players as well).

experienced with v0.1.3-alpha-335-g2f32bc0

**Comment by andreas-eberle** [comment]
This was fixed a while ago.
