### ISSUE TITLE
Incorrect building material distribution order

### ISSUE THREAD

**Issue by krichter722** [jsettlers/settlers-remake#205]
It can happen that building materials are not distributed in order (see [this video](https://richtercloud.de:447/index.php/s/gWp19NvsTjZsSFQ) for an example).

The reason is unclear, it might happen when building materials are no longer supplied from available resources, but settlers need to wait for them to be produced. The issue can happen after an hour of game play as well. It seems reproducible 100 % of time with the sequence of building in the video.

experienced with v0.1.3-alpha-338-g09c8631

**Comment by andreas-eberle** [comment]
Hi @krichter722,

what exactly do you mean? In your video, I don't see anything wrong. Can you give me a more detailed explanation?

Best regards

**Comment by krichter722** [comment]
The house should get the last stone delivered before the buildings ordered after it. At 1:05 you can see a settler picking up a stone, but not delivering it to the house.

**Comment by abledbody** [comment]
I believe you're assuming that buildings are supposed to be supplied in the order in which they're constructed. The original game had random distribution, where as Jsettlers supplies the closest first. (I think) While it would probably be quite productive to supply them in order it probably will either remain this way, or behave more like the original settlers in the future.

**Comment by abledbody** [comment]
Speaking of which, if you need to you can just set the building to high priority.

**Comment by andreas-eberle** [comment]
I think this should be fixed already.
