### ISSUE TITLE
Could not find/load graphic file

### ISSUE THREAD

**Issue by seb321** [jsettlers/settlers-remake#206]
Hi,
(sorry for my English),
When i'm running jsettlers i get error:

>seb321@seb321-K54HR:~/Pobrane/set/JSettlers$ ./JSettlers.jar 
Warning: Could not load LocaleSuffix [_pl]. Falling back to next file.
Warning: Could not load LocaleSuffix [_pl_PL]. Falling back to next file.
Could not find/load graphic file 01
Could not find/load graphic file 11
java.lang.NullPointerException
	at jsettlers.graphics.map.draw.ImagePreloadTask.run(ImagePreloadTask.java:121)
	at java.lang.Thread.run(Thread.java:745)
Could not find/load graphic file 12
java.lang.NullPointerException
	at jsettlers.graphics.map.draw.ImagePreloadTask.run(ImagePreloadTask.java:189)
	at java.lang.Thread.run(Thread.java:745)
Could not find/load graphic file 03
Could not find/load graphic file 03
Could not find/load graphic file 03
Could not find/load graphic file 03
Could not find/load graphic file 03
Could not find/load graphic file 03
Could not find/load graphic file 03
Could not find/load graphic file 03
Could not find/load graphic file 03
Could not find/load graphic file 03
Could not find/load graphic file 03
Could not find/load graphic file 03
Loading Sequence number 28
Could not find/load graphic file 03
Could not find/load graphic file 03
Could not find/load graphic file 03
Could not find/load graphic file 03
Could not find/load graphic file 03
...

Game runs, but i don't see buttons, buildings etc.
After installation I choosed folder with unziped settlers files(Gfx, Snd), i don't know what i'm doing wrong.
Ubuntu 14.04
Help!

**Comment by andreas-eberle** [comment]
From what package did you unzip the Gfx and Snd files?

**Comment by seb321** [comment]
From amazons demo(link is in instruction).

**Comment by bluec0re** [comment]
Found out that the Amazon Demo is inconsistent regarding the gfx capitalization:
```
siedler3_00.f8007e01f.dat  Siedler3_08.f8007e01f.dat  siedler3_16.f8007e01f.dat  Siedler3_46.f8007e01f.dat  siedler3_83.f8007e01f.dat
Siedler3_01.f8007e01f.dat  Siedler3_09.f8007e01f.dat  siedler3_17.f8007e01f.dat  Siedler3_47.f8007e01f.dat  siedler3_84.f8007e01f.dat
siedler3_02.f8007e01f.dat  siedler3_10.f8007e01f.dat  Siedler3_40.f8007e01f.dat  Siedler3_48.f8007e01f.dat  siedler3_85.f8007e01f.dat
Siedler3_03.f8007e01f.dat  Siedler3_11.f8007e01f.dat  Siedler3_41.f8007e01f.dat  siedler3_70.f8007e01f.dat  siedler3_99.f8007e01f.dat
siedler3_04.f8007e01f.dat  Siedler3_12.f8007e01f.dat  Siedler3_42.f8007e01f.dat  siedler3_71.f8007e01f.dat
siedler3_05.f8007e01f.dat  Siedler3_13.f8007e01f.dat  Siedler3_43.f8007e01f.dat  siedler3_80.f8007e01f.dat
Siedler3_06.f8007e01f.dat  Siedler3_14.f8007e01f.dat  Siedler3_44.f8007e01f.dat  siedler3_81.f8007e01f.dat
Siedler3_07.f8007e01f.dat  Siedler3_15.f8007e01f.dat  Siedler3_45.f8007e01f.dat  siedler3_82.f8007e01f.dat
```

This leads to the loading problems under *nix systems (where capitalization of filenames is important). After renaming all files to lowercase ``s`` everything works fine. Maybe it's possible to try titled filenames as a fallback if the lowercase variant could not be loaded?
