### ISSUE TITLE
Read original maps

### ISSUE THREAD

**Issue by codingberlin** [jsettlers/settlers-remake#211]
It should be possible to read the original game maps in the remake.

**Comment by codingberlin** [comment]
@tomsoftware would you mind to help us here with your knowlede, you collected in your repository? https://github.com/tomsoftware/sied3

**Comment by codingberlin** [comment]
@andreas-eberle @michaelzangl What do you think about transforming the original maps when jsettlers is started once (when the maps weren't transformed yet) into the new map format and store them in the maps dir?

**Comment by michaelzangl** [comment]
This might prove to be difficult. We use the same graphics, but our game grid has many differences. We can attempt to translate the maps but we might have problems in translating the images.

Our main goal should be to support an intuitive, good map editor and create our own set of maps.

So far, supporting those files is not planed, although the file format should not make any difficulties.

**Comment by codingberlin** [comment]
@michaelzangl When we know what the bits and bytes of the original map format means (e.g. Water Level 1) we can transform it into the new map format (Water Level 1) which can be read by the remake.

**Comment by andreas-eberle** [comment]
I think the best way would be to implement a loader for the original maps which implements the jsettlers.common.map.IMapData interface. This interface defines all the information required for creating a new MainGrid (i.e. for loading the map to start a game) and can also be used to load the map into the MapEditor.

I would not transform the maps into our map format. This is because 
* we would need the loader implementing the IMapData interface anyways (at least it must supply the same information). So converting them is actually one step more that just reading them on demand.
* we probably cannot transform the maps and ship them with the game (as we might not have the right to do so)
* if we provide a stable way to read the maps on demand, every user could just use his favorite maps which will include maps we don't know.
* by making it possible to directly start working on these maps with our MapEditor, people can develop there maps further with our tools and then easily create maps with our map format.

**Comment by codingberlin** [comment]
I agree. Currently you will find prototype code in the branch I created: https://github.com/jsettlers/settlers-remake/blob/feature_original_maps/jsettlers.logic/src/jsettlers/logic/map/OriginalMapLoader.java
Because first I have to understand how the original map format works.
When I (or we) got it, then I will refactor the code so that it fits into the game as a MapLoader which gives IMapData and MapFileHeader (which is needed by the map lists, isn't it?)

**Comment by tomsoftware** [comment]
What's missing?

As you can see:
https://github.com/jsettlers/settlers-remake/pull/230#event-461021927
the feature is working.

Known issues:
- Map creater can not save the maps
- Replay does not work/compile (I don't know nothing about this feature)
- scaling of map hight and resouce amount may still wrong
- ... ???

What's new:
- remake-maps are renamed to ".rmap"
- original ".map" and ".edm" can be loaded

**Comment by codingberlin** [comment]
I'll take a look at the issues:
* Map creator can not save the maps (@tomsoftware what is meant by that? Are you not able to create a map with the map creator and save it then to *.rmap ?)
* Replay does not work/compile
* scaling of map hight and resouce amount may still wrong
* #231 scrollbar bug

When:
* #233 (#231 (scrollbar bug)) is merged
* Buildtool is green
... I'll create a copy of this branch where is a feature freeze (but not a code freeze) From this branch I'll create a PR so that we can finalize/clean the code and merge it into master. I'll take responsibility to sync the changes from the PR into the original map branch were we can implement more features

**Comment by codingberlin** [comment]
I finished the scaling of map hight.

**Comment by codingberlin** [comment]
I finished the scaling of resource amount.

**Comment by codingberlin** [comment]
I fixed the runAutoReplayIT build by regenerating the replay files. They contained .map instead of .rmap in their stream.

**Comment by codingberlin** [comment]
@tomsoftware I updated the MapCreatorApp so that all the maps can be listed within the open dialog. I was able to create a new map and save it. A *.rmap was created. Does this fix the issue mentioned above: "Map creator can not save the maps"?

**Comment by tomsoftware** [comment]
@codingberlin:
- MapCreatorApp: thanks for fixing :+1: , I found another bug and fixed it.
- Map heigh: I think using ~0.5 as scaling factor is theoretically the best BUT then, playing the map differs very mutch from original (see image below). I think it's cause the remake alows mutch higer mountains. So the value 255 in original map heigh means about 85 in remake and 127 in remake would mean 381 in original...
(see image: you can't build on the mountains if factor is 0.5).
![remake_map_check_scale_2](https://cloud.githubusercontent.com/assets/3290888/11104070/d8262ad2-88c6-11e5-9f3f-e05e7b3f33c2.png)

I set up a pull request with my fixes. 

Thanks :-)

**Comment by andreasb242** [comment]
@codingberlin I think this bug can be closed? It's working :-)
