### ISSUE TITLE
Cannot drag-select units on high terrain

### ISSUE THREAD

**Issue by abledbody** [jsettlers/settlers-remake#215]
When units are standing on high terrain they are not selectable with mouse dragging.

**Comment by andreas-eberle** [comment]
I also experienced this issue in the game. I think it is not depending on the terrain type, but on the height of the terrain. 

@michaelzangl: I think we already had this issue a long time ago. Maybe it was reintroduced?

**Comment by justangel** [comment]
I have a similar problem
