### ISSUE TITLE
do you plan to implement online multiplayer (not just LAN games)

### ISSUE THREAD

**Issue by Jayflux** [jsettlers/settlers-remake#226]
That would be amazing if you did
I would be happy to help any way i can

**Comment by andreas-eberle** [comment]
Hi @Jayflux,

the game already supports online multiplayer games. I also have a server running which should be configured as default server. So if you just start a multiplayer game, it is already a online multiplayer game. 

Best regards,
Andreas

**Comment by Jayflux** [comment]
@andreas-eberle I mean in terms of the chat server, so you can go online and see if anyone else is on etc. Just like how the original did it.
 
I didn't see any of that when i clicked the multiplayer option
