### ISSUE TITLE
Wrong animations sequences are used / gfx-animation file is not used

### ISSUE THREAD

**Issue by tomsoftware** [jsettlers/settlers-remake#234]
-> the "movables.txt" has some bugs. e.g. 
STONECUTTER, BEND_DOWN, STONE, SOUTH_WEST = 11, 27,  0, 4

{File Sequence Frame}
(11 27 0), (11 27 1), (11 27 2), (11 27 3)

need to be the sequence:
(11 27 0), (11 27 0), (11 27 1), (11 27 1), (11 27 2), (11 27 2), (11 27 3), (11 27 3)

Solution:
use the in original animation sequences from gfx file (e.g. "siedler3_15.7c003e01f.dat")

Pro:
- the original sequences contain<br>
  {File, Sequence, Frame, TorsoFile, TorsoSequence, TorsoFrame, ShadowFile, ShadowSequence, Flags}<br>
  Flags: may be sound playback;<br>
  the ShadowFrame is missing -> think it is has the same value as Frame]<br>
- adding shadows or new buildings may mutch easier

Contra:
- Default walk animations are missing in original animation sequence
- May some original animation sequences are wrong (I think they fix some in the different Settlers versions)

Final Solution:
Use additional kind of entry in "movables.txt" e.g.:

 # type, action, material, direction = file, sequence index, start, duration
STONECUTTER, BEND_DOWN, STONE, SOUTH_WEST = 11, 27,  0, 4

 # type, action, material, direction ~ file, animation index
STONECUTTER, BEND_DOWN, STONE, SOUTH_WEST ~ 15, 23

so we can decide to use the build in animation or make it by our own.

Done so far:
Read animation sequences form gfx file

=> May you can create a new branch so I can merge in and you can help :-) :
https://github.com/tomsoftware/settlers-remake/tree/feature_improve_gfx_file_reader

Thanks, Thomas

**Comment by justangel** [comment]
hi, in gold edition version 1.60 GFX file index 15 not have any GFX data on it

**Comment by michaelzangl** [comment]
I updated the movable table to use OriginalImageLink objects. That abstraction allows us to define new sequence types. This will allow us to implement the image lookup for what you suggested.

**Comment by andreas-eberle** [comment]
Closing this in favor of #573.
