### ISSUE TITLE
Android - separate gameplay into its own activity

### ISSUE THREAD

**Issue by Sylapse** [jsettlers/settlers-remake#255]
Hi everyone, my first post here. Very excited to find out about JSettlers! :D

Splitting the Android UI into two activities could help to tidy things up in preparation for implementing the remaining UI features. A menus activity to display all fragments related to starting/joining a game. And a game activity for the gameplay, shows the loading screen when started, followed by the game itself.

Benefits:
- Simplify fragment management code.
- The main menus need not be locked into landscape like the game UI. Particularly appropriate on phones.

**Comment by andreas-eberle** [comment]
@michaelzangl: Do you see any issues with this proposal? @Sylapse already talked to me an proposed to implement the changes himself.

**Comment by michaelzangl** [comment]
The main menus currently do not really need to have the landscape in the background. I only added this to increase game startup time: While the user is still in the main menu, the graphics for landscape and trees are already loaded. The same GL context is used in the game.

@Sylapse Feel free to try it, it would be interesting to see how much cleaner it gets.

**Comment by Sylapse** [comment]
Thanks guys, I'll give it a go. Still trying to work out if I can realistically get up to speed at this point and this seems as good a place to start as any since I'm mainly an Android developer.

**Comment by andreas-eberle** [comment]
@Sylapse: Any news here? Did you find the time?

**Comment by Sylapse** [comment]
Hi @andreas-eberle, I made a small start but never quite got into it properly. Me and my cousin got funding for our business idea which was great news for us but didn't leave much time for hobby projects!

I ran into a problem that stopped me making progress, if I can get past that then I would like to carry on. 

I figured that for Android it would be really nice if rotation was enabled for the gameplay and if the game would carry on running in the background when the user presses the home button. So I thought I would hold the gameplay objects (the MapContent) in an Android service and then have a gameplay fragment with the views that gets the MapContent from the service. So even if the views got destroyed and recreated (which happens a lot in android due to rotation and things) they would just connect back to the same ongoing game.

The problem I get is that the second time i bind the views to the gameplay objects, the graphics glitch out. The game is still going on and the controls work.

Here is the code in the game fragment which works the first time. (GameProvider is just an interface that returns the same MapContent got from the service)

	public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
		View view = inflater.inflate(R.layout.fragment_map, container, false);
		GameProvider gameProvider = (GameProvider) getApplication();
		
		Region goRegion = new Region(Region.POSITION_CENTER);
		Area goArea = new Area();
		goArea.add(goRegion);
		
		GOSurfaceView goView = new GOSurfaceView(getActivity(), goArea);
		((FrameLayout) view.findViewById(R.id.frameLayout)).addView(goView);
		
		goRegion.setContent(gameProvider.getMapContent());
		return view;
	}


But when you rotate and the MapContent is being used for a second time it ends up looking like this


![screenshot_20160526-093949](https://cloud.githubusercontent.com/assets/10612949/15578245/03edd6cc-2360-11e6-8ea5-8e5b82c0eac2.png)



Tried lots of variations but either didn't work at all or get the same result. Maybe the MapContent isnt the right thing to try and reuse. Or maybe there's some way it can be reset to work with new fragment/views after rotation.

If you've got any advice I will definitely have another look!

**Comment by michaelzangl** [comment]
You need to invalidate the android graphics context the way swing does it. The texture handles are already there and have a method that tells if they are still valid. You need to check if the active android graphics context has changed. If it has, graphics should automatically be reloaded.

**Comment by andreas-eberle** [comment]
@Sylapse: Feel free to ask @michaelzangl whenever you have questions regarding the graphics or Android. He created most of that stuff and will be able to answer your questions.

Anyways, thanks for trying to continue contributing and good luck for your business!

**Comment by Sylapse** [comment]
Thanks @michaelzangl 

Just fired up the project and managed to find the necessary invalidate code. Adding it in fixes the problem :D 

I look forward to doing some more work on it now. I also pulled in the latest changes and it's great to see how much you guys have achieved. Switching to Gradle is very convenient for my dev setup. I can run the android and swing applications both from Android Studio!

**Comment by Sylapse** [comment]
Hi guys, @andreas-eberle @michaelzangl 

I had a play with this again yesterday and today and thought it would make sense to post an early version incase you have some feedback.

It's very basic so far but it does test out my two main goals which were.
1. Separate activities
        - One for the menu screen fragments
        - Another for the loadingbar and gameplay fragments
2. All screens support rotation

So far you can only start a new single player game. Also once you are in the game you can't access any of the controls yet. Also the game will keep running in the background until you manually close the app (swipe it away from the recent apps drawer).


https://www.dropbox.com/s/r4bl8qtzsfymz0x/bitrise-signed-jsettlers.main.android-release-unsigned.apk?dl=0

**Comment by andreas-eberle** [comment]
@Sylapse: Should I close this in favor of your newer ticket #516 with the status of your changes?

**Comment by Sylapse** [comment]
Yes please close
