### ISSUE TITLE
water works not collecting water

### ISSUE THREAD

**Issue by JAPETH007** [jsettlers/settlers-remake#262]
I am placing water works near water but I keep getting the error message of "Cannot find work_Waterworks.

**Comment by andreas-eberle** [comment]
Did you place it near a river or near the sea? A waterworks cannot take water from the sea, as that is salt water. Only the water from rivers can be taken.

**Comment by Zervox** [comment]
I'd say he didn't build it around rivers as I've not been able to replicate an error like this.

**Comment by andreas-eberle** [comment]
@JAPETH007: Is this still an issue?

**Comment by andreas-eberle** [comment]
Closing this due to missing response. Please reopen if this is still a problem.
