### ISSUE TITLE
Can JavaFX be used for our UIs?

### ISSUE THREAD

**Issue by andreas-eberle** [jsettlers/settlers-remake#264]
As our main menu UI is terrible at the moment, we need to develop a new one (see issues #141 and #140). As JavaFX is the new frontend library of Java it was planned to use it for these UIs. 

However, it seems like JavaFX is not implemented in the OpenJDK yet. In my opinion, we cannot use JavaFX if we cannot support OpenJDK out of the box. 

Therefore this issue is for discussion on how to make this work or to decide if we need to go with Swing instead of JavaFX.

From what I heard, there are several options:
* Bundle the JVM with the JSettlers executable. 
   * Advantage: The game is always started with a fixed JVM version => no JVM-version problems.
   * Disadvantage: We have to supply a JVM for every platform and therefore have to manage the versions and check them on differing operating systems. 
* It might be possible to "bundle" the [OpenJFX](https://wiki.openjdk.java.net/display/OpenJFX/Main) libraries with the executable. Does anybody have experience with this / does anybody know if this is possible?

**Comment by codingberlin** [comment]
Another yet not solved JavaFX problem is the stretching of the (dynamically generated) background images. ([see this stackoverflow post](http://stackoverflow.com/questions/34556467/how-to-stretch-a-dynamically-created-background-image-in-both-directions-in-java))

I see two advantages of JavaFX:
(1) separation of structure, style and code
(2) JavaFX is supposed to replace Swing in the future

But on the other hand I can downgrade the advantages
(1) The separation of structure, style and code is very important for me as a web developer of a website with an huge amount of pages **but** in this subproject of the settlers remake we we deal with around 10 pages (menus) so I think this advantage is still an advantage but just a very small one for our context.
(2) [Oracle FAQ says] (http://www.oracle.com/technetwork/java/javafx/overview/faq-1446554.html#6) that ```Swing will remain part of the Java SE specification for the foreseeable future``` so there is no fear that we need to rework our Swing UI tomorrow. Comparing the features of JavaFX and Swing I can't see a must have at the JavaFX site. More likely I see missing stuff at the JavaFX site (e.g. the scaling of background images when you can't use css)

Another point of view for me is that if you have a lot of men power you can try out a lot of innovative stuff and you can go further when you hit the first problems. But we implement this remake in our free time and I think that it is more motivative when can focus on implementing features and have no distraction of problems like "how to bundle every possible JRE for every possible platform or how to include JavaFX into the JAR ect.)

So my conclusion would be: Stopping JavaFX and implementing in Swing.

What is your opinion?

**Comment by andreas-eberle** [comment]
I fully agree with you @codingberlin.

Furthermore it seems that we have more development power already experienced with SwingUIs (e.g. @andreasb242). 

Therefore I will close this discussion. @codingberlin, you can start with a new SwingUI for the main menu.

**Comment by andreasb242** [comment]
:-)
