### ISSUE TITLE
AI destroys own towers at the border to the enemy

### ISSUE THREAD

**Issue by andreas-eberle** [jsettlers/settlers-remake#266]
Sometimes the AI (tested with ROMAN_VERY_HARD) destroys its own towers next to the border to an enemy. This causes the AI to lose own ground.

**Comment by Zervox** [comment]
I wanted to reply to this as I've only encountered this once in regards to border towers, I've noticed the AI can also remove towers in the main area of their base(not unlike how some players would do it if their borders are very strong) the problem with this is that the AI does not build castles or large towers bulked together like a human would if they want to have a bit of buffer time against enemy attack.

**Comment by Zervox** [comment]
After further testing, it seems at one point it will not only destroy border towers, but it will destroy them for whatever reason I cannot see until it has no towers left causing it to idle even though it has all the resources and buildings to expand or keep attacking, but it just idles troops keeps staying in base, placing a tower for them will cause them to build again and attack, but it will eventually destroy the built tower and then go back to idling again.

**Comment by codingberlin** [comment]
Could someone upload a replay-file and tell me the time(s) when an AI destroys towers next to the border to an enemy?

Currently I implemented the AI as follows:
- destroy hinterland towers -> to get the swordsman back to occupy another tower
- destroy towers which are not in the main land (partition) of the AI -> in the most cases the enemy would re-occupy the occupied tower which should be prevented so that the enemy does not get back all of the occupied land but just the half

**Comment by andreas-eberle** [comment]
@Zervox: That the AI idles when is has not towers left is a feature: When you have no towers left, you lost the game and therefore your chance to interact with it (does not work for normal players, yet).

**Comment by andreas-eberle** [comment]
@codingberlin: You can reproduce it by playing the current master (418f5f6eafef6a2aea03a07ceb93937ab9d1407d) with options 
```--all-ai --fixed-ai-type=ROMAN_VERY_HARD```

Play the map "6 players fun" and fast forward to about minute 33. Around this time, the yellow player will destroy multiple towers at his border to the blue player. 

I think this is better for you than a replay, as it should be always reproducible but involves the AI (replays don't actually run with the AI, but only its recorded actions).

**Comment by codingberlin** [comment]
Thx for the map and time. I was able to find and fix the bug.
