### ISSUE TITLE
AI fights early in the game and loses all soldiers

### ISSUE THREAD

**Issue by andreas-eberle** [jsettlers/settlers-remake#267]
The ROMAN_VERY_HARD AI tends to fight very early in the game. After the fight no or almost no soldiers are left but no weapon production is established yet. Afterwards the AI is not able to aquire any new land which is required to have the space or resources to build up the weapon production. Therefore the AI is practically dead after that fight.

**Comment by Zervox** [comment]
I've not seen the AI do this yet unless there is enemy border very close to theirs, you can force the AI to react aggressively by just having soldiers pass the borders then retreat, the ai will not stop the units unless there are soldiers crossing the border elsewhere after you've made this taunt.
