### ISSUE TITLE
Set AI working area & destroy AI building

### ISSUE THREAD

**Issue by s3zwirni** [jsettlers/settlers-remake#271]
It's actual possible to set the working area to all buildings of the AI e.g. the wood cutter. Additional it's possible to destroy each AI building by using the crush-button.

Using: 
* Windows 10
* Java 1.8.66
* JSettler 0.2 Alpha

**Comment by andreas-eberle** [comment]
This is actually a "feature" at the moment. The idea is to let you see what the AI does, how it works and detect mistakes it makes or help it when there is a problem or test if that help can improve the behavior. 

I will add a comment about this to the news on the website. Thanks for mentioning it. Of course this will not be possible in the future.
