### ISSUE TITLE
Android '1/2/3' button not working

### ISSUE THREAD

**Issue by DerKrawallkeks** [jsettlers/settlers-remake#276]
I hope I'm not spamming the issue section, just delete my issues if they've got an obvious reason (like noone has been working on the certain fuction).

Issue: The 1/2/3 button on the bottom right corner isn't working. The problem is that I don't know what it's supposed to do..:)

Xperia Z3 Android 5.1.1

**Comment by michaelzangl** [comment]
It is supposed to be a placeholder to just reserve space for one button (for now).

**Comment by andreas-eberle** [comment]
Fixed with the new AndroidUI
