### ISSUE TITLE
Android 'Map-button' not working

### ISSUE THREAD

**Issue by DerKrawallkeks** [jsettlers/settlers-remake#277]
The green Map-like button on the bottom right corner of the HUD isn't working. Is it supposed to have a function? It would be useful..
:)

Xperia Z3 Android 5.1.1

**Comment by andreas-eberle** [comment]
Actually, it is supposed to have a function one day... at the moment it is not implemented yet.

**Comment by andreas-eberle** [comment]
Fixed with the new Android UI.
