### ISSUE TITLE
Making map player number problem

### ISSUE THREAD

**Issue by Zervox** [jsettlers/settlers-remake#281]
Creating a map with lets say 10.
reducing amount of players through settings requires restarting the editor for the place object for player to update, however you can still accidentally place objects for them causing the map to go into endless load in game if you forget to restart the map editor.
There is no error related in the map error lists even after restarting the editor. 

This can however be fixed by increasing the player number to the player index of the player you've placed objects for and place the start point, or by removing the objects for the non existing player id.

**Comment by michaelzangl** [comment]
Two Problems here: The map editor not checking the max player number and the game logic not aborting a load on an invalid file.

**Comment by andreas-eberle** [comment]
@andreasb242: Did you implement a check for the player number in your new map editor PR?

**Comment by andreas-eberle** [comment]
@andreasb242: Did you implement a check for the player number in your new map editor PR?

**Comment by andreasb242** [comment]
No, there are multiple errors with the player number:
* No warning if the user does not exist (it's only checked if the ground and the settlers are the same player)
* The user selection combobox is not updated, if the user count changes
* If you import a map with more than 16 Players it cannot be loaded

Should I fix it in the enhancement-new-mapeditor-ui branch?

Why is there a limit to 16 player, the colors can be calculated with a HSV Color model?

**Comment by andreas-eberle** [comment]
@andreasb242: You could fix it in a branch based on the enhancement-new-mapeditor-ui branch. After I merged that into the master, we can then have a look at these fixes. 

Regarding the number of players: The game logic should be able to handle up to 127 players without any adaptions. Maybe the rendering of the soldiers could have problems... @michaelzangl, would do you say?

**Comment by michaelzangl** [comment]
GUI currently uses 11 player colors. After that, the colors repeat.

The GUI can handle player numbers up to 127 (some get the same color). I don't think we need more.

**Comment by andreasb242** [comment]
127 are enough for sure, but 11 are to less, because of the import of of existing maps...

Ok, I'll create a new branch for this player fix.

@andreas-eberle You may assign the ticket to me?

**Comment by andreas-eberle** [comment]
@andreasb242: Unfortunately, I cannot assign you the ticket (github...). Nevertheless, feel assigned to it ;)

**Comment by codingberlin** [comment]
(ignore my assignment ... it was a wrong click)
