### ISSUE TITLE
Create a Discord?

### ISSUE THREAD

**Issue by Silentspy** [jsettlers/settlers-remake#286]
For communication around Jsettlers! :+1:

**Comment by abledbody** [comment]
Ooo. Yes please!

**Comment by jimnordb** [comment]
Any update on this? :dart:

**Comment by andreas-eberle** [comment]
I didn't know Discord as of yet. I will have to look into it.

**Comment by jimnordb** [comment]
Awesome! i can help if set it up if you need so, its rather straight forward.

**Comment by andreas-eberle** [comment]
Does anyone of you have experience with Gitter.im? It seems to be integrated with github quite well.

**Comment by jimnordb** [comment]
This is the first time i see it, seems rather polished :D

**Comment by janisozaur** [comment]
Hi, at https://github.com/OpenRCT2/OpenRCT2 we use gitter. Stick away from that service, the very few minutes I've spent with discord proved it was much better and easier to use.

**Comment by Hiradur** [comment]
Why not use IRC instead? A lot of FOSS projects have their own channel on [freenode](https://freenode.net/) so many FOSS developers already use it and are familiar with it. It also makes conversations easy and user friendly (i.e. registration is optional).

> Does anyone of you have experience with Gitter.im? It seems to be integrated with github quite well.

It is integrated with GitHub reasonably well but it's also inherently buggy and resource hungry. Nothing too bad but it can be annoying at times.

**Comment by andreas-eberle** [comment]
Hi everyone,

I just set up a Discord Server (at least I hope I did it ;) ). I would like to test this with the people on this ticket first. So here is the link https://discord.gg/2hVV4u6 . I'm looking forward to seeing you on the server to get a feeling for this platform.

Thanks + cu
