### ISSUE TITLE
New resource management

### ISSUE THREAD

**Issue by michaelzangl** [jsettlers/settlers-remake#302]
Currently, jsettlers manages those resources:

- The resources directory containing the maps, building.xml-Files, savegames ...
- The GFX/SND/MAP directory of Settlers 3
- The config.prp with the path to those directories.

I suggest changing this and handling those 3 categories:

## User settings

In this directory (`%APPDATA%/.jsettlers`, `~/.jsettlers`) we can store the settings for the current user.

This contains a central settings file. We can use xml or a property file for this.
Examples:
```XML
<settings>
<settlers-dir path="..." version="gold"/>
<settlers-dir path="..." version="demo"/>
<last-used-games>
<last-used-game id="..." time="..."/>
</last-used-games>
</settings>
```

```Properties
settlers.dir.1 = ...
settlers.dir.1.version = ...

lastused.1.name = ...
lastused.1.time = ...
```

We also add the resources that can be changed by the user. This includes:
* A map directory that contains maps installed or created by the user
* The savegame directory.

## Resources

Those are the resource files that are boundled with settlers. In the long run it would be best to pack them all into one jar and extract them when needed. Android already handles them that way.

This is basically the resources directory in jsettlers.common without the savegames.

## The Settlers 3 directories
We store a list of Settler 3 directories. The list is stored in the user settings.

We prompt a directory on game startup if no directory exists.

This is the directory where the GFX, Map and SND direcotries reside in.

Fo looking up resources, we can scan through all available directories. I would suggest simply prefering the gold directories for GFX files. For Map files, we can scan for non-dupplicate maps.

## Implementation

We already have `ResourceManager`. It handles the Resources (building xml files, ...). There is a special version for android that allows us to pack them into the APK file. This also works fine for maps packed with the program.

I would like to add a `SettingsManager`. It should be the main entry point to accessing resources.

We can then use `SettingsManager#getResources()` to access the resources. Resources should be read-only.

We should add a new `SavegameManager` accessible by `SettingsManager#getSavegames()`. It handles all saved game states.

We also need the ability to get a settler directory. `SettingsManager#getOriginalResources(type)`, where type is one of MAP, GFX, SND. This returns a OriginalResourceDirectory. That class automatically merges multiple directories depending on the type.

We change the ImageProvider/SoundManager code to use the SettingsManager.

**Comment by andreasb242** [comment]
>In this directory (%APPDATA%/.jsettlers, ~/.jsettlers) we can store the settings for the current user.

On Windows %APPDATA%/.jsettlers is the right folder, but on Linux the folder ~/.config/jsettlers should be used. There are already to much Applications which save the settings directly to the root of the home folder.
On Mac OS X the default save folder is: ~/Library/jsettler

Example code (out of a working example):
```java
			if (Boolean.parseBoolean(Config.get("portable"))) {
				writePath = Config.getRootDirectory(); // absolute Path to Jar File
			} else {

				String home = System.getProperty("user.home");

				switch (OS.getOs()) {
				case LINUX:
					writePath = home + "/.config/" + Config.getApplicationPath();
					break;
				case WINDOWS:
					writePath = System.getenv("APPDATA") + File.separator + Config.getApplicationPath();
					break;
				case MAC:
					writePath = home + "/Library/" + Config.getApplicationPath();
					break;
				default:
					writePath = home;

				}
			}

```
I usually support a portable version, which saves the settings relative to the .jar file, so it can be started from USB Stick. But I think it's not needed here...

I would use different Property file for different types of data:
* Paths: Settler III Path(s)
* Last used maps in the game
* Last opened maps in the Editor (I already created that File)
* Editor settings (not yet needed)
* Game settings, e.g. User Name, Server settings, whatever

Splitting up into different files solves the synchronisation problem, if you save all settings to one file, opens the game and the editor, and they are both writing the settings to the same file, may some entries get lost.

**Comment by andreas-eberle** [comment]
I don't think it is a good idea to bundle the resources folder into the .jar file. When we keep them seperate, it will be easier to provide a incremental update (e.g. only change the jar file, if the resources stay the same). I see no advantage of packaging the resources into the .jar file. It only makes it (much) bigger. Additionally, the map files should be accessible in a folder and not "hard coded" into the executable.

**Comment by andreas-eberle** [comment]
Closing this, as the system has been changed with the switch to gradle.
