### ISSUE TITLE
Development guide -> "gen" missing in jsettlers.graphics not jsettlers.common

### ISSUE THREAD

**Issue by aligator** [jsettlers/settlers-remake#314]
hi
I just tried to setup the project and I noticed the following:
In the Wiki:

> trouble building the projects, the following steps might help:
> Clean and build all the projects.
> Make sure the project jsettlers.common has a source folder called "gen". If not, refresh the project. If it still isn't there, try to explicitly build the project (right click on the project -> "Build Project").
> After that, rebuild all projects (without a clean!). You can do this with "CTRL + B".
> If there is still a project refusing to build, try to explicitly build that one via right click on the project -> "Build Project".
> If you know how to fix this trouble, I'm looking forward to your hints and code changes ;).

but jsettlers.common had the gen-folder.
I noticed that it was missing in jsettlers.graphics. After refresh of jsettlers.graphics it worked.

so could you add this to the wiki?

**Comment by andreas-eberle** [comment]
Thanks for the hint. I fixed the wiki page.
