### ISSUE TITLE
Random crash when switching to full screen

### ISSUE THREAD

**Issue by andreas-eberle** [jsettlers/settlers-remake#319]
I just ran into a crash of the JVM when I switched to full screen. I attached the crash dump. As it only appeared once as of yet, I don't know how to reproduce it.

EDIT: This happend on the current master.

[hs_err_pid3188.txt](https://github.com/jsettlers/settlers-remake/files/190698/hs_err_pid3188.txt)

**Comment by andreas-eberle** [comment]
Just happend again. It seems that it is problematic to switch to full screen when a lot of messages are incomming (I replayed a large game with a lot of "cannot find X messages" beeing displayed). During replay the messages are also incomming very fast, as the game logic is running on max speed.

[hs_err_pid912.txt](https://github.com/jsettlers/settlers-remake/files/190708/hs_err_pid912.txt)

**Comment by andreas-eberle** [comment]
This might be caused in correlation with the newest Oracle JDK 8u77. I didn't have this crash before and now (after I switched to the new JDK today) I can reproduce it very often.

**Comment by codingberlin** [comment]
I had these crashs very often with the old swing GUI but never with the new.

**Comment by andreas-eberle** [comment]
I can confirm that. I cannot reproduce it with the new swing main menu.

**Comment by andreas-eberle** [comment]
I did not experience this any more and since the new main menu is merged into the master, I close this issue.
