### ISSUE TITLE
Builders stops carriers when building

### ISSUE THREAD

**Issue by stumpdk** [jsettlers/settlers-remake#32]
When working on a building, the builders make the incomming carriers wait and queue up. This is especially an issue with larger buildings like Large Residence.
As far as I remember, in the original Settlers, the carriers could unload, while the builders were working.

**Comment by stumpdk** [comment]
Can this be accomplished by setting brcklayer.visible = false when running tryToBuild() in BricklayerStrategy? That way, the bricklayer won't occupy the space for the carrier.

**Comment by andreas-eberle** [comment]
No, it can't. The thing is, that only movables that are on the grid, can/will be rendered. So in JSettlers any position on the map can only be occupied by one single Movable. The way to go is to calculate a path around the other movable.

Solving such conflicts is already done for many cases with the Movable.push() mechanics. I will have to check what needs to be done exactly for this case.
