### ISSUE TITLE
use gradle for build?

### ISSUE THREAD

**Issue by daviddawson** [jsettlers/settlers-remake#33]
Would you consider a PR to convert the build to gradle rather than ant?

That will allow use of other IDE and also give good integration with the new android developer tools that are gradle based.

**Comment by daviddawson** [comment]
This would also fix issue #4

**Comment by adamjryan** [comment]
I second this. Would a submission to begin a migration to Gradle be welcome?

**Comment by andreas-eberle** [comment]
I never worked with Gradle, but if you can create the required build configurations and want to submit them as PR, go ahead. I don't care what system is used, as long, as it does it's work ;) This includes  Swing Build, Android Build, low compile times during development / incremental builds and if possible, different build profiles (development and release) would be great. 

@michaelzangl: Do you see any obstacles?

**Comment by daviddawson** [comment]
Great, I'll work with Adam to prepare a PR. I'm travelling for the next few days and will get to this on friday/ saturday.

Very excited to revisit settlers again :-). Thanks for the project.

**Comment by andreas-eberle** [comment]
What is the status on this?

**Comment by krichter722** [comment]
The eclipse/ant build process (I never used ant on the command line because I didn't want to figure out the name of build files and the instructions for eclipse were provided) doesn't build very reliably (maybe that why it's so fast ;)). Removing `target/` manually and requesting "Build all" in eclipse doesn't recreate `target` - something I'd expect from a build tool.

referring to v0.1.2-alpha-550-gaea1344

**Comment by daviddawson** [comment]
That would be because 'build all' in eclipse doesn't actually invoke ant, it uses the local eclipse setup, essentially driven by the eclipse config file that the ant build produces.

**Comment by michaelzangl** [comment]
Yes, the current ant system is a bit hacked and only designed to work as long as people use the "normal" eclipse way of building.

This is why I am very open to using an other build system. There are several things to consider here:
- We have lots of auto-generated stuff. Most of it is currently created in an ant-specific way. You either need to integrate the old ant scripts or you need to change the source of the texture, layout and android-image processing methods.
- Android seems to have official support for gradle: http://tools.android.com/tech-docs/new-build-system/user-guide
- Dependency resolution is not trivial. Currently, most dependencies are added in eclipse. So the current main build script won't get them all and eclipse may have problems after a git update if you do not reload the resources (F5).

**Comment by daviddawson** [comment]
The gradle setup actually handles most of that already. The big thing missing is android support. Last time I spent time on it, everything else pretty much worked as expected, all libs resolved correctly etc.

Should work well enough with the gradle support in all major IDEs as it's a standard multi module gradle build. 

Android may present some fun though.

**Comment by andreas-eberle** [comment]
This is fixed in the meantime.
