### ISSUE TITLE
Sort Class Members

### ISSUE THREAD

**Issue by homoroselaps** [jsettlers/settlers-remake#330]
The member order of many classes is arbitrary and prevents from good orientation in the code base. 
A one time Member sort in many classes would solve these problems.

**Comment by homoroselaps** [comment]
This will lead to immense merge problems with local branches. Which could be solved by sorting the files in the same order before merging.

**Comment by michaelzangl** [comment]
Which order do you want to sort the members in?

I am strictly against an alphabetical order. Currently, most members are ordered ins some way (general->specific, important->unimportant, final->non-final, ...). I know we are not consistent on it but we would gain nothing by sorting them in any automated way.

**Comment by andreas-eberle** [comment]
I agree with Michael. In the game logic classes, the order is mostly oriented on having methods close to their usages so you don't have to jump through the whole file to find them / work on them. 

Furthermore, in Eclipse, the "Outline" view shows all class members. You can also sort them and hide some types of members you don't want to see. I guess there is something like this in most IDEs. Maybe this is what you actually need @homoroselaps?

**Comment by homoroselaps** [comment]
I am using this Outline already, which is not so useful any more if you have 150+ entries. If you would know which direction to scroll I think it might be helpful aka sorted methods in code. I tried sorting them by hand by its way to much work to get them in a logical order. Maybe you know some tool, where I can move whole methods?

**Comment by michaelzangl** [comment]
In Eclipse, go to the "Outline" view.

Drag a method/member to change the order.

Select + `Shift` + `Alt` + `R` to rename.

You can also sort the outline view without changing the source (Press the A/Z button)

**Comment by michaelzangl** [comment]
If there are no more questions, I would mark this message as resolved.
