### ISSUE TITLE
Code question

### ISSUE THREAD

**Issue by homoroselaps** [jsettlers/settlers-remake#335]
I am having serious trouble understanding what the intention of this code is. It may let some soldiers stop going to the requestedTargetPosition if they are already in state PATHING. May @andreas-eberle or someone else help me with it?

jsettlers.logic.movable.strategies.soldiers.SoldierStrategy
```
Checks preconditions before the next path step can be gone.
@param pathTarget
           Target of the current path.
@param step
           The number of the current step where 1 means the first step.
@return true if the path should be continued<br>
        false if it must be stopped.

protected boolean checkPathStepPreconditions(ShortPoint2D pathTarget, int step) {
	if (state == ESoldierState.INIT_GOTO_TOWER) {
		return false; // abort previous path when we just got a tower set
	}
	boolean result = !((state == ESoldierState.SEARCH_FOR_ENEMIES || state == ESoldierState.HITTING) && step >= 2);
	if (!result && oldPathTarget == null) {
		oldPathTarget = pathTarget;
	}
	if (state == ESoldierState.GOING_TO_TOWER && (!building.isNotDestroyed() || building.getPlayer() != super.getPlayer())) {
		result = false;
	}
	if (enemy != null && state == ESoldierState.SEARCH_FOR_ENEMIES && isEnemyAttackable(enemy, false)) {
		result = false;
	}
	return result;
}
```

**Comment by michaelzangl** [comment]
This code aborts the current path on some conditions, mainly that the target of the path is no longer there.
Some cases in which this might happen:
- Soldier wants to occupy a tower but the tower gets destroyed
- Enemy around the soldier was found (this is the annoying behaviour of soldiers going after enemies even if you told them not to...)

Some things that may help you understand this:
rename `result` with `canContinueWithPath`
replace all `result = false` with `return false`
Replace that first long condition with:
```

isAttackingEnemies = state == ESoldierState.SEARCH_FOR_ENEMIES || state == ESoldierState.HITTING;
canContinueWithPath = !isAttackingEnemies || step < 2;
```
