### ISSUE TITLE
Use visitor pattern for iterating over areas.

### ISSUE THREAD

**Issue by michaelzangl** [jsettlers/settlers-remake#339]
Currently they allocate tons of ShortPoint2D objects.

We can save them in: 
- MovablePathfinderGrid#calcDecentralizeVector
- MovablePathfinderGrid#informMovables
- MovablePathfinderGrid#getEnemyInSearchArea
- ObjectsGrid#informObjectsAboutAttackable
- LandscapeGrid#areAllNeighboursOf
- MovableGrid#informMovables

**Comment by andreas-eberle** [comment]
Already implemented with CoordinateStream.
