### ISSUE TITLE
Market cargo requests don't trigger production.

### ISSUE THREAD

**Issue by JKatzwinkel** [jsettlers/settlers-remake#356]
When requesting tools like shovels, hammers and pick axes at a market, one would expect a tool smith to forge those tools. But tool smith don't care and market never receives what it wants.

**Comment by JKatzwinkel** [comment]
Is there even a way yet to request production of tools without at the same time getting the respective special workers? It looks like tool production is exclusively invoked based on that `WorkerCreationRequest` linked list in `PartitionManager`.

**Comment by andreas-eberle** [comment]
At the moment there is no way of manually requesting tools to be produced.

However, the market should not trigger the creating of tools, as this is clearly not its responsibility. In fact, we need to make the tool production menu working for this. 

Therefore I created #357 to coordinate this task and will close this one.
