### ISSUE TITLE
Make manual tool production possible.

### ISSUE THREAD

**Issue by andreas-eberle** [jsettlers/settlers-remake#357]
At the moment, tools are only produced when a worker is needed. We should also make it possible to manually request the tool production (e.g. to be able to send tools with donkeys).

**Comment by DerKrawallkeks** [comment]
Manual tool request should overwrite the automatic management. A manually requested tool should not just be put into the queue of possible automatic production that might be going on

**Comment by andreas-eberle** [comment]
Was already implemented.
