### ISSUE TITLE
Nightly Builds

### ISSUE THREAD

**Issue by jimnordb** [jsettlers/settlers-remake#359]
Is someone willing to setup a travis or something we could to get nightly builds?

**Comment by michaelzangl** [comment]
Travis is already set up.

We don't do nightly builds, we do builds after every addition to master (or to any other branch).

**Comment by jimnordb** [comment]
That is good! is having a dedicated page on the official web page that links the latest builds in the plans?  also do you have a link to downloading the specific packages for each build? @michaelzangl https://travis-ci.org/  only seem to output logs. even though the log states its uploading a zip file.

**Comment by michaelzangl** [comment]
We are generating a ZIP file. Travis is not meant to release any artefacts. There is limited support for pushing it on to some web services but we currently do not intend to do this (mostly because of security issues)
