### ISSUE TITLE
Soldiers not going to new tower

### ISSUE THREAD

**Issue by derfuhrer2007** [jsettlers/settlers-remake#361]
Android

On settler craters map when beginning I have created a tower in the S, NW and NE. 

The tower on the S does not get populated with soldiers at all, while the other 2 get bowmen on top.

Samsung Note 3 Android 5.0 No mods

**Comment by derfuhrer2007** [comment]
Found that if you send a swordsman close to a tower that is empty he will go in, so it is probably the distance limit that needs adjusting.

Pretty good game for now, keep up the good work.

**Comment by derfuhrer2007** [comment]
Probably same issue, this time on the PC.

Tower swordsman was killed, attacker killed after that by a small task force, but none would enter the tower. They are just casually sitting next to it, having a smoke.

![screenshot 3](https://cloud.githubusercontent.com/assets/18621498/14937448/124608d8-0f25-11e6-9638-4c282f976d29.png)

**Comment by andreas-eberle** [comment]
I also saw this bug once or twice. I will have a look. Can you attach the replay logfile of the PC match?

**Comment by derfuhrer2007** [comment]
Not sure. How do I get that?

Also I can't seem to find how to save the game on the PC.

**Comment by andreas-eberle** [comment]
In your directoy where you have the JSettlers.jar file, you should find a folder named `resources` containing a folder named `logs`. In this folder, you can look for the folder of the game by starting time of the game and the map you played. Please zip that folder and attach it to the issue.

**Comment by derfuhrer2007** [comment]
[2016-04-24_14-55-32_Settler_Craters.zip](https://github.com/jsettlers/settlers-remake/files/246384/2016-04-24_14-55-32_Settler_Craters.zip)
I think this is it.

Btw, is there a way to save the game on the PC?

**Comment by andreas-eberle** [comment]
You can save by pressing F2. But this should change in the future...

**Comment by tinco** [comment]
Can confirm that it's specifically a swordsman that needs to be in range.

**Comment by andreas-eberle** [comment]
I fixed that in PR #418.

**Comment by andreas-eberle** [comment]
I'm closing this issue, as it should be fixed.
