### ISSUE TITLE
Extremely low fps, Android, Motorola X Play

### ISSUE THREAD

**Issue by BastarB** [jsettlers/settlers-remake#362]
I get extremely low fps when running the game, like 4,5fps in the menu and 0,5fps in game, running it on Motorola X Play.

**Comment by michaelzangl** [comment]
Are you starting from android studio using instant run?

**Comment by andreas-eberle** [comment]
Did you use the current master with Android Studio? If yes, you most likely have instant run activated. Then please try this: https://github.com/jsettlers/settlers-remake/wiki/Setting-up-Android-Studio

**Comment by andreas-eberle** [comment]
@BastarB, any news on this one?

**Comment by andreas-eberle** [comment]
Closing due to lack of response. Hopefully the new Android App has already fixed it. If not, please reopen.
