### ISSUE TITLE
AI crashs due to ArrayIndexOutOfBounds

### ISSUE THREAD

**Issue by andreas-eberle** [jsettlers/settlers-remake#364]
The AI crashes if it is used on a map where the land comes close to the map border. It seems that most (if not all) implementations of `IBestConstructionPositionFinder` are lacking bound checks before calling `aiStatistics.getMainGrid().getPartitionsGrid().getPlayerIdAt(workAreaPoint.x, workAreaPoint.y)`.

The issue is reproducible most of the times (due to the random seed) with the attached map.

Furthermore, it looks like the code of the implementations of `IBestConstructionPositionFinder` look very simmilar. Is it possible to reduce the amount of duplicate code?

[fun_map_center_bot_4-2016-04-19_19-29-11.zip](https://github.com/jsettlers/settlers-remake/files/233082/fun_map_center_bot_4-2016-04-19_19-29-11.zip)

**Comment by andreas-eberle** [comment]
@codingberlin: Do you have time to take a look at this?

**Comment by codingberlin** [comment]
Yes, I will fix this.
