### ISSUE TITLE
building does not produce when it's build next to players border (here: goldmine)

### ISSUE THREAD

**Issue by codingberlin** [jsettlers/settlers-remake#374]
In this save game of the current master you can see how the blue gold miner fails to put a basket of gold ore right next to the borderland of the player which results in zero gold ore production by the mine.

I assume that this bug happens with other buildings as well.

[buggy-gold-mine.zmap.gz](https://github.com/jsettlers/settlers-remake/files/236409/buggy-gold-mine.zmap.gz)

**Comment by andreas-eberle** [comment]
This was caused by a bug in the job definition of the goldmine. The worker tried to leave the protected area of the building. However, only that area can be garanteed to be walkable. So I think this is limited to the goldmine only.
