### ISSUE TITLE
Images of building are flickering during construction

### ISSUE THREAD

**Issue by andreas-eberle** [jsettlers/settlers-remake#383]
#### Screenshots of issue
![unbenannt](https://cloud.githubusercontent.com/assets/9267365/14848007/ec56388e-0c6b-11e6-9122-149e149311a4.png)
![unbenannt2](https://cloud.githubusercontent.com/assets/9267365/14848008/ec5ae64a-0c6b-11e6-8bd3-7febca401872.png)

#### Steps to reproduce
* Start map "Volcano Mountain" with current master (12bad540765621341e430c7bce0c2057d3b0fc7b)
* Build a gold melt at position (199|267) (this is the left gold melt in the screenshots)
* Wait until it is fully constructed
* Build a second gold melt at position (208|268)
* Watch the construction of that gold melt to see the images change.

Note: It may depend on the zoom and screen position. Sometimes it is flickering, sometimes the "more complete" image is in the background instead of in the foreground.

**Comment by abledbody** [comment]
This is the same bug as #225. I've noticed that it does change with respect to the screen position.

**Comment by andreas-eberle** [comment]
Closing as duplicate of #225.
