### ISSUE TITLE
absent images of buildings (android)

### ISSUE THREAD

**Issue by lubomyr** [jsettlers/settlers-remake#389]
absent images of buildings
version: master (27.04.2016) c96e78f69ae21d5e81bcd8d57732f534d28e3c87
device: Commodore Pet (Android 5.0)
Screenshot
![settlers-remake](https://cloud.githubusercontent.com/assets/468950/14864295/027ba2e2-0cc2-11e6-8b85-39f76ba4661d.jpeg)

**Comment by michaelzangl** [comment]
Dupplicate of #208
