### ISSUE TITLE
English locales with strings having wrong language

### ISSUE THREAD

**Issue by Fantu** [jsettlers/settlers-remake#39]
settlers-remake/jsettlers.common/resources/localization/labels_en_US.properties is only with few strings correct, other must be translated to english.

As I told in #12 I started new transifex project to make easier and faster translation, when there will be full template (english) correct will be possible start using it:
https://www.transifex.com/projects/p/settlers3-remake/

**Comment by michaelzangl** [comment]
labels_en_US.properties is in English now.
