### ISSUE TITLE
Selecting a soldier type selects the directly clicked soldier twice

### ISSUE THREAD

**Issue by derfuhrer2007** [jsettlers/settlers-remake#391]
When I double click on a type of soldier around the barracks, I also get the ones on the way to the barracks counted as well. They appear in the left menu, however they don't get selected (green dot) or follow the given order.
![screenshot 1](https://cloud.githubusercontent.com/assets/18621498/14927301/8e4057a2-0e6e-11e6-83d4-04eb5dce5937.png)

**Comment by andreas-eberle** [comment]
Can you attach the replay of this? [Please always attach the replay in such "game logic seems to be wrong" situations](https://github.com/jsettlers/settlers-remake#found-a-bug-report-it).

**Comment by derfuhrer2007** [comment]
[2016-04-29_23-54-38_mountain_lake.zip](https://github.com/jsettlers/settlers-remake/files/246399/2016-04-29_23-54-38_mountain_lake.zip)

**Comment by andreas-eberle** [comment]
Thanks for the replay. The issue is that the soldier you directly select when doing a double click, is actually selected twice.
