### ISSUE TITLE
Build script should zip/tar JSettlers in a folder

### ISSUE THREAD

**Issue by andreas-eberle** [jsettlers/settlers-remake#4]
The build script should create a zip/tar file that unpacks to a folder containing the files of the game.

**Comment by justangel** [comment]
1 - compile sources from Eclipse
2 - use "build.ant" for build zip/tar and other files jSettlers in a "target" folder, and this work perfect for me

**Comment by andreas-eberle** [comment]
What I meant was that the content of the zip or tar fie should be a folder called JSettlers containing the game's files. At the moment the game files are directly zipped/tared.

**Comment by justangel** [comment]
I see, sorry, my fault, did not understand what it was about, I confirm the fact of the problem about zip/tar files

**Comment by justangel** [comment]
fix for that problem http://1drv.ms/1CUwj4p a few corrections one build file

**Comment by andreas-eberle** [comment]
Thanks for the changes!

**Comment by justangel** [comment]
Thanks for the project of my favorite part of the game
