### ISSUE TITLE
Gradle build fails

### ISSUE THREAD

**Issue by JKatzwinkel** [jsettlers/settlers-remake#412]
Gradle won't build anything for me, apparently because I don't have an `ANDROID_HOME` env. Output is:

```
FAILURE: Build failed with an exception.

* Where:
Build file '/mnt/data/codes/Java/settlers-remake/go.graphics.android/build.gradle' line: 15

* What went wrong:
A problem occurred evaluating project ':go.graphics.android'.
> SDK location not found. Define location with sdk.dir in the local.properties file or with an ANDROID_HOME environment variable.
```

Also, my eclipse workspace doesn't build anymore. What do I have to do to be able to build the swing target again?

**Comment by andreas-eberle** [comment]
You will have to create a `local.properties` file in the project root (see also https://github.com/jsettlers/settlers-remake/wiki/Setting-up-IntelliJ-IDEA-%28Linux,-WIndows,-OSX%29#when-you-have-the-android-sdk-manager-installed)

However, atm, I don't know if the project is really working with Eclipse any longer. @michaelzangl tried to make it work with eclipse and gradle. However, I recommend switching to Android Studio, as it is currently the only IDE that can really handle the project. IntelliJ is not really working, because it has a bug in combination with the Android stuff...

**Comment by michaelzangl** [comment]
You should be able to work in eclipse mars. There may be minor dependency issues (eclipse tells you that it is not working, but it is). Simply import the gradle project.

**Comment by homoroselaps** [comment]
Is it possible to skip the android gradle build?! I have no way to test it and need the space on my harddrive...

**Comment by michaelzangl** [comment]
Is `gradle :jsettlers.main.swing:run` not working?

**Comment by homoroselaps** [comment]
1. I dont have gradle. I use the gradlew.bat in the root folder instead. On the website they told me I should use it if one is shipped with the project.
2. It tells me:
```
λ gradlew :jsettlers.main.swing:run --info
Starting Build
Settings evaluated using settings file 'C:\master\settings.gradle'. << This file does not exist
Projects loaded. Root project using build file 'C:\Users\...\Projects\Java\settlers-remakeH\build.gradle'.
Included projects: [root project 'settlers-remakeH']
Evaluating root project 'settlers-remakeH' using build file 'C:\Users\...\Projects\Java\settlers-remakeH\build.gradle'.
Compiling build file 'C:\Users\...\Projects\Java\settlers-remakeH\build.gradle' using SubsetScriptTransformer.
Compiling build file 'C:\Users\...\Projects\Java\settlers-remakeH\build.gradle' using BuildScriptTransformer.

FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Users\...\Projects\Java\settlers-remakeH\build.gradle' line: 92

* What went wrong:
A problem occurred evaluating root project 'settlers-remakeH'.
> Task with path ':jsettlers.mapcreator:run' not found in root project 'settlers-remakeH'.

BUILD FAILED

Total time: 7.677 secs
Stopped 0 compiler daemon(s).
```
If I comment line 92 out, the error is in line 93, line 124...

3.I found an android sdk on my drive. Created a local.properties file:
`failed to find target with hash string 'android-15' in: C:\Program Files (x86)\Android\android-sdk`
But I have an platforms/android-19 folder?!

**Comment by michaelzangl** [comment]
1. Yes, it is the same
2. Hmm, this is odd. I'll have a look into it.
3. When compiling for android you need the exact target version. It is not the same as java where some newer versions will do as well.

**Comment by homoroselaps** [comment]
1. I dont have gradle. I use the gradlew.bat in the root folder instead. On the website they told me I should use it if one is shipped with the project.
2. It tells me:
```
λ gradlew :jsettlers.main.swing:run --info
Starting Build
Settings evaluated using settings file 'C:\master\settings.gradle'. << This file does not exist
Projects loaded. Root project using build file 'C:\Users\...\Projects\Java\settlers-remakeH\build.gradle'.
Included projects: [root project 'settlers-remakeH']
Evaluating root project 'settlers-remakeH' using build file 'C:\Users\...\Projects\Java\settlers-remakeH\build.gradle'.
Compiling build file 'C:\Users\...\Projects\Java\settlers-remakeH\build.gradle' using SubsetScriptTransformer.
Compiling build file 'C:\Users\...\Projects\Java\settlers-remakeH\build.gradle' using BuildScriptTransformer.

FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Users\...\Projects\Java\settlers-remakeH\build.gradle' line: 92

* What went wrong:
A problem occurred evaluating root project 'settlers-remakeH'.
> Task with path ':jsettlers.mapcreator:run' not found in root project 'settlers-remakeH'.

BUILD FAILED

Total time: 7.677 secs
Stopped 0 compiler daemon(s).
```
If I comment line 92 out, the error is in line 93, line 124...

3.I found an android sdk on my drive. Created a local.properties file:
`failed to find target with hash string 'android-15' in: C:\Program Files (x86)\Android\android-sdk`
But I have an platforms/android-19 folder?!

**Comment by homoroselaps** [comment]
@michaelzangl Is there already some process on this?

**Comment by homoroselaps** [comment]
Is debugging possible with eclipse? If IntelliJ/Android Studio is fully supported I may just switch to it...

**Comment by andreas-eberle** [comment]
You need to install the android sdk 15 in you Android SDK manager.
