### ISSUE TITLE
Add image index mapping for different GFX file types (Amazon Demo, Original 1.60 and Gold)

### ISSUE THREAD

**Issue by andreas-eberle** [jsettlers/settlers-remake#416]
The big tower shown in the screenshot contains 
- 2 PIKEMAN_L1
- 1 SWORDSMAN_L1
- 3 BOWMAN_L1

![unbenannt](https://cloud.githubusercontent.com/assets/9267365/15072745/46de4348-1395-11e6-893c-64df1ccc325d.png)

**Comment by andreas-eberle** [comment]
The images are correct when you use the Amazon Demo GFX files. We will need to add a mapping of the indexes between Amazon Demo, Gold version and original version (with Patch 1.60).

**Comment by tomsoftware** [comment]
may this can be done automatically by using the internal mapping / sequence data?
https://github.com/jsettlers/settlers-remake/issues/234

**Comment by andreas-eberle** [comment]
Closing this in favor of #573.
