### ISSUE TITLE
AI should try to connect its land 

### ISSUE THREAD

**Issue by andreas-eberle** [jsettlers/settlers-remake#434]
When the AI attacks an enemy and takes over some of its land, it should try to connect that land to its own land. Then, its economy could benefit from the loot auqired in the fight.

**Comment by andreas-eberle** [comment]
@codingberlin: Isn't this already implemented?

**Comment by codingberlin** [comment]
You`re right. This was implemented as one pioneer stragey with priority 4 of 9 pioneer target finders. - I close this issue.
