### ISSUE TITLE
AI should finish weak enemies to profit from their goods

### ISSUE THREAD

**Issue by andreas-eberle** [jsettlers/settlers-remake#435]
The AI often does not attack weak players / players with only a few towers left for a very long time. Instead, it seams that it focuses on the strongest player. 

While defending and attacking the strongest player is important, the AI should also attack and finish the weak players. This way, it can profit from their goods and improve its economy in the fight against the stronger players.

**Comment by andreas-eberle** [comment]
@codingberlin: I think this is already implemented, isn't it?

**Comment by codingberlin** [comment]
Yes you're right. The code was changed so that the weakest instead the strongest enemy is attacked. Thus while fighting down the already weakest enemy the weakest enemy keeps the weakest enemy and the next attack target is still the same player until he is finished.

I close the issue.
