### ISSUE TITLE
JSettlers crashes on game start with EXCEPTION_ACCESS_VIOLATION

### ISSUE THREAD

**Issue by andreas-eberle** [jsettlers/settlers-remake#440]
The game crashed when starting a match. The game crashed several times already but I haven't figured out a way to reproduce it. It happens randomly. The game is compiled to a jar from the current enhancement-better-ai-building-lists with commit ba83d3a.

Log output:

```
E:\Games\JSettlers_bot_32\JSettlers>java -jar jsettlers.jar
No default command line options file found.
Options loaded: {}
Source: (file:/E:/Games/JSettlers_bot_32/JSettlers/JSettlers.jar <no signer cert
ificates>)
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0xffffffffa3855120, pid=2640, t
id=4684
#
# JRE version: Java(TM) SE Runtime Environment (8.0_77-b03) (build 1.8.0_77-b03)

# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.77-b03 mixed mode windows-amd64
 compressed oops)
# Problematic frame:
# C  0xffffffffa3855120
#
# Failed to write core dump. Minidumps are not enabled by default on client vers
ions of Windows
#
# An error report file with more information is saved as:
# E:\Games\JSettlers_bot_32\JSettlers\hs_err_pid2640.log
Compiled method (c1)     648  524       3       jsettlers.common.Color::convertT
o32Bit (50 bytes)
 total in heap  [0x0000000002a87d10,0x0000000002a887c0] = 2736
 relocation     [0x0000000002a87e30,0x0000000002a87ef0] = 192
 constants      [0x0000000002a87f00,0x0000000002a87f20] = 32
 main code      [0x0000000002a87f20,0x0000000002a88440] = 1312
 stub code      [0x0000000002a88440,0x0000000002a884d0] = 144
 oops           [0x0000000002a884d0,0x0000000002a884d8] = 8
 metadata       [0x0000000002a884d8,0x0000000002a884f8] = 32
 scopes data    [0x0000000002a884f8,0x0000000002a886f8] = 512
 scopes pcs     [0x0000000002a886f8,0x0000000002a887b8] = 192
 dependencies   [0x0000000002a887b8,0x0000000002a887c0] = 8
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
#
```

[hs_err_pid2640.log.txt](https://github.com/jsettlers/settlers-remake/files/266831/hs_err_pid2640.log.txt)

**Comment by andreas-eberle** [comment]
@michaelzangl: Do you have an idea? I didn't find the stack trace in the logfile...

**Comment by daviddawson** [comment]
Possibly looks like this http://www.java.com/en/download/help/exception_access.xml

**Comment by michaelzangl** [comment]
No, this happens after VM startup somewhere during image reads / conversion to normal bitmaps, possibly during or close to convertTo32Bit (which is JIT compiled but not inlined).

You can view the assembly for that method by using `-XX:+UnlockDiagnosticVMOptions -XX:+PrintAssembly` (you need hsdis for this, setting up for the fist time can be difficult.)

Why is the main thread even reading GUI images? Normally, this should be done on a separate thread.

**Comment by andreas-eberle** [comment]
I wasn't able to reproduce the bug since a while, so I'm closing this.
