### ISSUE TITLE
Soldier not joining the fight

### ISSUE THREAD

**Issue by derfuhrer2007** [jsettlers/settlers-remake#447]
The second soldier was just going back and forth, not joining the fight at all.
[2016-05-20_23-48-08_Nice_Map (2).zip](https://github.com/jsettlers/settlers-remake/files/275848/2016-05-20_23-48-08_Nice_Map.2.zip)
![screenshot 10](https://cloud.githubusercontent.com/assets/18621498/15448253/3342d72c-1f7a-11e6-9936-500cf3c9b38c.png)

**Comment by derfuhrer2007** [comment]
Again ![screenshot 13](https://cloud.githubusercontent.com/assets/18621498/15448817/05e8beb2-1f8a-11e6-978c-e7d43da03e1b.png)

**Comment by andreas-eberle** [comment]
The first screenshot actually shows a problem, I've seen myself. I will have a look into it.

The second screenshort shows a problem that was already solved in master.
