### ISSUE TITLE
place mines on some fan-made orginal maps not possible

### ISSUE THREAD

**Issue by ekle** [jsettlers/settlers-remake#459]
on some original maps, it is impossible to place a mine on most parts of mountains.
![mine](https://cloud.githubusercontent.com/assets/1193892/15567370/426ec292-2326-11e6-9bb9-e061162b4e01.png) 
one map where you can place only very few mines is:
https://mapbase.siedler3.net/640-16-deepforest
on some smaller mountains its impossible to place mines at all.

**Comment by tomsoftware** [comment]
the problem is that the original-game and the remake are using differnet scalinging for the height.
see #235  
> tomsoftware commented on 12 Nov 2015

and

> codingberlin commented on 14 Nov 2015

this bug/feature was "fixed"/"introduced" in #235

**Comment by andreas-eberle** [comment]
as @codingberlin told me, there is also the problem that in the original game, mines do not have to be placed completely on mountain. However, this is the case in the remake. Therefore I will  have to take a look how much of the mine's ground needs to be mountain to adjust our calculations.

**Comment by michaelzangl** [comment]
A quick improvement would be to allow the mines to be built on the mountain borders.

**Comment by codingberlin** [comment]
I checked the original settlers.

It seems so, that you can place mines when their center is on mountain or mountain border:

Screenshot of the original map editor:
![editor](https://cloud.githubusercontent.com/assets/6422616/15759565/751bc7fa-290f-11e6-8c4b-a8beead7d6f5.png)

Original in-game screenshot (slightly broken but focus on the green dots)
![settlers1](https://cloud.githubusercontent.com/assets/6422616/15759566/751f943e-290f-11e6-9058-4b780dae9032.png)

Original in-game screenshot while placing the mine (slightly broken, too)
![settlers2](https://cloud.githubusercontent.com/assets/6422616/15759567/7532939a-290f-11e6-9950-a6d64130bf73.png)

**Comment by andreas-eberle** [comment]
@codingberlin: Thanks for the research. I will adapt the code.

**Comment by codingberlin** [comment]
@andreas-eberle here is the test map with which I created the screenshots above.
[minen.map.zip](https://github.com/jsettlers/settlers-remake/files/299046/minen.map.zip)

**Comment by andreas-eberle** [comment]
@codingberlin: Thanks. In PR #477, it looks like in your screenshot from the orignal game.
