### ISSUE TITLE
Building selection state is not reset when movables are selected

### ISSUE THREAD

**Issue by andreas-eberle** [jsettlers/settlers-remake#46]
When you select a building to construct in the menu, the building construction marks are displayed (red and green dots). When now selecting some movables, the building construction is not canceld, but the movables are selected and the list of selected movables is displayed. 

Expected behaviour: The building creation should be canceld (so that the construction marks are removed) and the selected movables should be displayed (as before).

**Comment by michaelzangl** [comment]
Fixed in b7436fa6fe60d4d94e5ef4e4b63c5010048fad5b
