### ISSUE TITLE
Carriers waiting in line to deliver

### ISSUE THREAD

**Issue by derfuhrer2007** [jsettlers/settlers-remake#463]
Seems the carriers are waiting for the builders to finish to deliver the material
![screenshot 14](https://cloud.githubusercontent.com/assets/18621498/15585314/5838f720-239c-11e6-8027-6d68748e0b1e.png)
[2016-05-26_23-22-52_Volcano_Mountain.zip](https://github.com/jsettlers/settlers-remake/files/285030/2016-05-26_23-22-52_Volcano_Mountain.zip)

**Comment by derfuhrer2007** [comment]
Same thing happened with a soldier waiting in line, while there was an attack on the tower. It just stood there, waiting to get it, and got killed

**Comment by andreas-eberle** [comment]
This is already fixed.
