### ISSUE TITLE
Wood carried far away

### ISSUE THREAD

**Issue by derfuhrer2007** [jsettlers/settlers-remake#464]
For some reason these guys are carrying the wood to the other sawmill, which is further away.
[2016-05-26_23-22-52_Volcano_Mountain (2).zip](https://github.com/jsettlers/settlers-remake/files/285053/2016-05-26_23-22-52_Volcano_Mountain.2.zip)
![screenshot 15](https://cloud.githubusercontent.com/assets/18621498/15585727/71d4854e-239e-11e6-8efc-4584cfb0712a.png)

**Comment by andreas-eberle** [comment]
Well, this is not really a bug. It's more how the system is designed. The material distribution system ensures that all production buildings get their needed materials equally (in a round robin style). 

In most cases, this is a good idea, as it ensures that all production buildings get something to work on by preventing that one sawmill has a lot of trunks while another one has none.

When the system has chosen the sawmill that will get the next trunk, it looks for the one closest to the sawmill. However, if that one is quite far away, it will be carried all the way. 

I know this is not optimal. However, I will close this issue, as I currently see now way improving this behavior without making the overall distribution perform worse. Furthermore, this should only appear when the ammount of available materials is quite low.

**Comment by derfuhrer2007** [comment]
Are you sure it is working fine? As I was low on wood and the logs were just moved around, though the sawmills didn't have any work cuz they didn't have logs.

As you can see, there are 2 logs being carried in opposite directions.

**Comment by andreas-eberle** [comment]
I know, this isn't optimal. However, it is an inherent flaw of the current system, which probably cannot be removed without traiding it for other problems. I know it isn't perfect...

**Comment by derfuhrer2007** [comment]
Can you detail the algorithm to me, will try to devise a better one, as I am better at this than at coding. 

    On Friday, May 27, 2016 12:53 PM, Andreas Eberle <notifications@github.com> wrote:
 

 I know, this isn't optimal. However, it is an inherent flaw of the current system, which probably cannot be removed without traiding it for other problems. I know it isn't perfect...—

**Comment by derfuhrer2007** [comment]
What could be done is to calculate the travel time and only if the processing time (including queue) would be larger than the travel time (including queue at the other facility).This should keep carriers from going back and forth and also long distances uselessly, keeping the busy for no reason.Also, maybe doing this when a certain number of carriers are free and in the area might help. 

    On Friday, May 27, 2016 1:19 PM, Tibi Petculescu <derfuhrer2007@yahoo.com> wrote:
 

 Can you detail the algorithm to me, will try to devise a better one, as I am better at this than at coding. 

    On Friday, May 27, 2016 12:53 PM, Andreas Eberle <notifications@github.com> wrote:
 

 I know, this isn't optimal. However, it is an inherent flaw of the current system, which probably cannot be removed without traiding it for other problems. I know it isn't perfect...—
