### ISSUE TITLE
Food distribution not even

### ISSUE THREAD

**Issue by derfuhrer2007** [jsettlers/settlers-remake#466]
Coal seems to be getting all the food from the left fisheries, while the iron mines are not getting anything, though being empty. There should be somewhat even, not just sent to the closes one requiring food.

[2016-05-26_23-22-52_Volcano_Mountain (4).zip](https://github.com/jsettlers/settlers-remake/files/285089/2016-05-26_23-22-52_Volcano_Mountain.4.zip)
![screenshot 17](https://cloud.githubusercontent.com/assets/18621498/15586282/34f9729e-23a1-11e6-887d-5c4ae41cc95d.png)

**Comment by andreas-eberle** [comment]
I just rechecked with the current master. This is already fixed.
