### ISSUE TITLE
Kill gfx and sound after a fight

### ISSUE THREAD

**Issue by derfuhrer2007** [jsettlers/settlers-remake#467]
Seems odd, but there were kill graphics and sounds, but after the fight, out of the blue.
![screenshot 18](https://cloud.githubusercontent.com/assets/18621498/15586901/5f35e814-23a4-11e6-8c88-1b8a80e2ff64.png)
[2016-05-26_23-22-52_Volcano_Mountain (5).zip](https://github.com/jsettlers/settlers-remake/files/285137/2016-05-26_23-22-52_Volcano_Mountain.5.zip)

**Comment by derfuhrer2007** [comment]
Now seems to be stuck in a loop

**Comment by derfuhrer2007** [comment]
Was fixed when I destroyed the tower and then my soldier and enemy ai soul were shown at the same time.

**Comment by andreas-eberle** [comment]
This was fixed already. Invisible soldiers where killing the door of the tower over and over again.
