### ISSUE TITLE
Provide "nightly" builds of the master

### ISSUE THREAD

**Issue by andreas-eberle** [jsettlers/settlers-remake#472]
##### Problem
People that want to test and play the game with the newest features and bugfixes need to compile it themselfes. Not everybody can do this. This also leads to the creation of issues that are already fixed.

##### Proposal
Somehow provide builds of all commits to master (this means builds for every merged PR). 

##### Ways to do it
At the moment, I only see travis as a way to do this. There is the possibility to push builds to the repositiory. However, releases can only be pushed to github for tags. Therefore we'd need to create a tag for every commit on the master.

Does anyone have experience with something like that or knows a github project somehow managing "nightly" builds in a way we could also do it?

**Comment by codingberlin** [comment]
I talked with a colleague about that topic and he proposed to use the combination between a gradle build step and travis (which can get credentials) to build the artifact and upload (overwrite) it to AWS S3 or Dropbox because travis is running with every commit in the master.

**Comment by andreas-eberle** [comment]
Instead of an AWS or Dropbox, we could use the wordpress of the project webpage (www.settlers-android-clone.com). We should be able to put the file there and publish the link on the webpage.

Has anyone experience with something like that?

**Comment by michaelzangl** [comment]
The difficulty is to make it safe ...

I suggest adding an environment variable TRAVIS_PUSH_SECRET=abcd ([encrypted](https://docs.travis-ci.com/user/encryption-keys/))

We can then put a short PHP script on the server (untested):

```php
<?php
if ($_REQUEST["secret"] != "abcd") die("Invalid access token");
$target = "settlers-nightly.zip"
move_uploaded_file($_FILES["file"]["tmp_name"], $target) || die("cannot move file.");
```

We can also push multiple files this way.

We should then be able to upload using  `curl -F "secret=abcd&file=@my.file"`

**Comment by andreas-eberle** [comment]
Travis supports encrypted secrets that we can specify as project owners. Travis can then decode these secrets so they can be used to call an API.

**Comment by jimnordb** [comment]
is http://www.settlers-android-clone.com/ self hosted? in that case if its not on a shared web host it would be rather easy to implement a lets encrypt certificate on the webserver for a more secure solution

**Comment by andreas-eberle** [comment]
No, its a managed wordpress instance. I don't even have ftp access.

However, I cam accross the github pages stuff and saw a project using it for uploading their generated documentation. I think we could also use this and then link to this page from the project page.

**Comment by DerKrawallkeks** [comment]
I think finding a place to upload it is the smallest problem. I've got an ftp server, or dropbox like codingberlin suggested
