### ISSUE TITLE
destroyed towers still keep land occupied

### ISSUE THREAD

**Issue by ekle** [jsettlers/settlers-remake#483]
sometimes destroyed towers still keep land occupied with now way to change to owner.
attached a savegame where this happened.

version d6dcc99c0680b9cf612695dbb904fc9a4644368b

[save.zip](https://github.com/jsettlers/settlers-remake/files/303409/save.zip)  (map deepforrest)

**Comment by andreas-eberle** [comment]
Closing, as this was fixed already.
