### ISSUE TITLE
Interface problem

### ISSUE THREAD

**Issue by lefqa** [jsettlers/settlers-remake#491]
Hello, Dudes 🙂
I play the latest version of game on android.
Instead of buildings at me small icons with their quantity.
And in general the interface not such, as on screenshots and on the original version of game. Perhaps it is some bug? Maybe I have downloaded not that SND and GFX version to phone?
Also I don't know how to make geologists.
 I checked it for Galaxy S3, LG k550, Xiaomi Redmi Note 2,3
Last version of the game.
screenshots:
1. https://yadi.sk/i/uVnUuGPjtE9Ug
2. https://yadi.sk/i/VDYRg73qtE9ZK

**Comment by DerKrawallkeks** [comment]
Already been discussed in #208
Same for me^^ still no icons in the current version.

**Comment by andreas-eberle** [comment]
This should be fixed in the latest release.
