### ISSUE TITLE
Use retrolambda for Android to be able to use lambdas in platform crossing project parts

### ISSUE THREAD

**Issue by andreas-eberle** [jsettlers/settlers-remake#494]

**Comment by michaelzangl** [comment]
... Should not be that difficult. https://github.com/evant/gradle-retrolambda

**Comment by andreas-eberle** [comment]
I will wait with this until Android Studio 2.2 and the Jack&Jill build chain is released. With retrolambda alone there are some majore drawbacks (see discussion in #495).

**Comment by Sylapse** [comment]
On my fork I've updated to SDK24 and enabled Jack and can confirm official lambda support is working fine. So this should be taken care of when I PR

**Comment by andreas-eberle** [comment]
@Sylapse: We cannot simply update the SDK to 25. This means almost no one could play the game, as almost no one has Android 7.1. We need to stick to at max API level 19 (Android 4.4). Furthermore Jack&Jill doesn't work properly in some Windows environments (e.g. on my PC...)

**Comment by Sylapse** [comment]
@andreas-eberle It's fine to compile the project with the latest SDK, it will still run on older Android versions as long as the min sdk version is set to something lower. I currently have the min sdk version set to 15 and the target version to 25 so it will run on any device that is 15 any up. This way you get the benefits of the latest SDK and all of the up to date support library.

As for Jack&Jill, if it's more hassle than it is help to have this enabled then I'll remove it and use the regular listener syntax for now.

**Comment by andreas-eberle** [comment]
@Sylapse: Sorry, I understood you wrong. I thought you increase the MinSDK. As for Jack&Jill, keep it at the moment. When you're ready to merge and it is still not working (I'm still hoping for a patch), we can still replace it with retrolambda...
