### ISSUE TITLE
Enable Developing without AndroidSDK

### ISSUE THREAD

**Issue by homoroselaps** [jsettlers/settlers-remake#499]
How can I build + debug JSettlers without AndroidSDK. I have (very) limited disk space on my hard drive and no Android device to test it.
#496 fixed the building part!
What about debugging?

**Comment by michaelzangl** [comment]
It depends on what IDE you use for debugging.

You can always compile the app and then run it using java:
```
./gradlew assemble
java -jar ....jar -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=1044 ...
```

The exact syntax depends on the JVM used, please consult it's manual on how to start it in debug mode.

**Comment by homoroselaps** [comment]
Well for `gradle assemble` I get the error:
> A problem occurred configuring project ':go.graphics.android'.
> failed to find target with hash string 'android-15' in: C:\...\AndroidSDK

How can I specify to only assemble the non-android-part?

**Comment by michaelzangl** [comment]
You can use `:jsettlers.main.swing:assemble` (or whatever target you want)

**Comment by homoroselaps** [comment]
I still get the same error o.O

**Comment by homoroselaps** [comment]
I gave up and installed the necessary android dependencies...
Can you give me support for how to debug `jsettlers:main:swing` in _AndroidStudio_?

**Comment by andreas-eberle** [comment]
Simply right-click on the class jsettlers.main.swing.SwingManagedJSettlers and select "Run" or "Debug". After you did this once, you should have a run configuration in the toolbar from which you can run / debug it again and again.

**Comment by homoroselaps** [comment]
Thx. I just thought I has to be more difficult because of the gradle thingy...
In the end it's exactly like in Eclipse...
