### ISSUE TITLE
Java Files in Build folder

### ISSUE THREAD

**Issue by hetzge** [jsettlers/settlers-remake#5]
Some classes could not be resolved. As example jsettlers.common.images.TextureMap in jsettlers.graphics.map.draw.ImageProvider. The TextureMap.java is localted in the build folder (https://github.com/jsettlers/settlers-remake/blob/d3e225df6eb6342481955c52a1c4ecf1af87225c/jsettlers.common/build/jsettlers/common/images/TextureMap.java)

Or is there a special reason for that ?

**Comment by hetzge** [comment]
Oh i see ... i didn't run the buildfile createTexture.ant correctly.

**Comment by andreas-eberle** [comment]
Just a question: Has this not been run by eclipse automatically? It should be configured as a "Builder" in the project settings. If it wasn't, please reopen the ticket, so I can fix the configuration.

**Comment by hetzge** [comment]
I am not very experienced with ant. Because that i done it a little bit complicated. But i retried it with a fresh clone and it seams to build/start when i start the SwingMangedJSettler main class. The only thing i have to do first is creating a gen folder in the jsettlers.common Project.

**Comment by andreas-eberle** [comment]
Thanks, I updated the code to add the missing folder and fixed another bug in one of the android buildfiles.
