### ISSUE TITLE
small string error in english

### ISSUE THREAD

**Issue by Fantu** [jsettlers/settlers-remake#50]
I found a small string error in english:
big tmeple
that should be:
big temple

there are also other strings strange probably to improve

about translation project in trasifex probably can be good add a refer about it somewhere:
https://www.transifex.com/projects/p/settlers3-remake/
anyone can use it and should make easier and faster translation in any languages, from web, without programming experience, also with more people working on same translation in real time ecc...

**Comment by andreas-eberle** [comment]
Hi Fantu,

how is the work with transifex exactly? I joined your project there to translate our settlers 3 remake and was already able to change some buggy labels. But how are the changes propagated back into this repository? 

Furthermore, do you, as project maintainer, have an easy way to download all the labels files with their proper naming? I was only able to download the files one by one and with other filenames as in the repository. 

Another aspect: Is it possible to add a required label to all the translation files at once? I mean, if we have some new labels, they are needed in all the translation files. Do I have to copy them to all files, or is there a functionality to do this automatically. 

I think if there are solutions for these questions, we could really work with transifex.

Best regards + many thanks for your proposal,
Andreas

**Comment by Fantu** [comment]
Thanks for your reply.
About transifex:
I can't do same name in transifex for resources and mapcreator files because have same name (label_<language>.properties)
For now download/upload is manual but is possible automatize it with client and scripts with api.
For example this for another project:
https://bitbucket.org/Swyter/warband-acok-l10n/src
with settlers should be easier because conversion is not needed, transifex had already java properties files support.
I'll probably do at least small bash script in weekend probably.
A problem for automatic scripts can be wrong language code, for example "dk_DK" should be "da_DK" 
About russian will be the only and changed to "ru" or I must change it on transifex to "ru_RU" ?

When template language is updated all, transifex automatically update all languages, maintaining translations and adding/changing only lines added and changed, with acok in which each new version changes even thousands of strings transifex has saved me many hours of work.

About string error... "big tmeple" is still wrong

**Comment by Fantu** [comment]
another small writing mistake:
"big living house," should be "big living house"
