### ISSUE TITLE
White map

### ISSUE THREAD

**Issue by derfuhrer2007** [jsettlers/settlers-remake#502]
For some reason, the map is just white
![image](https://cloud.githubusercontent.com/assets/18621498/19104274/4cc0b5a4-8ae4-11e6-92db-02038b223485.png)

[2016-10-05_09-46-34_448_2Ph,M.plateau_replay.zip](https://github.com/jsettlers/settlers-remake/files/510255/2016-10-05_09-46-34_448_2Ph.M.plateau_replay.zip)

**Comment by michaelzangl** [comment]
How old is your graphics driver? I suppose it does not allow for sub-image updates. We need this feature for the minimap.

**Comment by derfuhrer2007** [comment]
Might be old, though latest available driver for win xp on this antique eeepc netbook

Sent from Yahoo Mail on Android 
 
  On Wed, 5 Oct, 2016 at 12:47, Michael Zangl<notifications@github.com> wrote:   
How old is your graphics driver? I suppose it does not allow for sub-image updates. We need this feature for the minimap.

**Comment by michaelzangl** [comment]
We decided not to fix this, since it seems to be an issue with an outdated graphics driver.
