### ISSUE TITLE
Selecting group of thieves/geologists

### ISSUE THREAD

**Issue by derfuhrer2007** [jsettlers/settlers-remake#504]
Seems it is impossible to select a group of thieves or geologists, you need to be going one by one
[2016-10-05_09-46-34_448_2Ph,M.plateau_replay.zip](https://github.com/jsettlers/settlers-remake/files/510265/2016-10-05_09-46-34_448_2Ph.M.plateau_replay.zip)

**Comment by derfuhrer2007** [comment]
Also had issues selecting soldiers, they were getting selected by dragging when a fight was going on, other than that i had to double click a type to send it around.

And this seems to have led to a crash 2h into the game.

[hs_err_pid2056.zip](https://github.com/jsettlers/settlers-remake/files/510979/hs_err_pid2056.zip)

**Comment by andreas-eberle** [comment]
Regarding the crash: What OS are you using?

**Comment by derfuhrer2007** [comment]
Old school win xp

Sent from Yahoo Mail on Android 
 
  On Wed, 5 Oct, 2016 at 18:30, Andreas Eberle<notifications@github.com> wrote:   
Regarding the crash: What OS are you using?

**Comment by andreas-eberle** [comment]
Closing this as double click can be used to select multiple settlers of the same type.
