### ISSUE TITLE
Soldier strength

### ISSUE THREAD

**Issue by derfuhrer2007** [jsettlers/settlers-remake#505]
It seems to vary from 68% to 42% for some reason.

I have sent the gold to the market and kept it there for now.
[2016-10-16_21-01-14_400-2-Close.zip](https://github.com/jsettlers/settlers-remake/files/532035/2016-10-16_21-01-14_400-2-Close.zip)

**Comment by derfuhrer2007** [comment]
Seems they dont get counted at the market, got down to 42% instantly

**Comment by andreas-eberle** [comment]
Like in the original game, gold placed on a market is not counted for the soldier strength. Therefore this works as expected. When my computer is repaired, I'll continue working on the stocks.
