### ISSUE TITLE
Wrong resource, building and unit animations after installing full version

### ISSUE THREAD

**Issue by krichter722** [jsettlers/settlers-remake#509]
After installing the german full version (without amazons/gold edition)
- Geologists put gold symbols for coal resources, empty symbols for iron and sulphur symbols for gold.
- Building limits are displayed with resource symbols for mountains on normal ground.
- Working areas are displayed with large red symbols which I don't recognize.
- Donkeys and priests are invisible.

Wrong resource, building limit and working area symbols (resources are coal, iron and gold from north to south):

![bildschirmfoto vom 2016-10-24 20-46-06](https://cloud.githubusercontent.com/assets/4369372/19659405/0e823dba-9a2c-11e6-84be-8c4a7faa6576.png)

There're no donkeys, but the iron is transported magically:

![bildschirmfoto vom 2016-10-24 20-47-24](https://cloud.githubusercontent.com/assets/4369372/19659438/32e5c2f8-9a2c-11e6-8a64-4d58b2b680aa.png)

A selected invisible priest (switching the window, e.g. to the screenshot program, makes it visible for an instant):

![bildschirmfoto vom 2016-10-24 20-49-30](https://cloud.githubusercontent.com/assets/4369372/19659485/6941c5ea-9a2c-11e6-89e2-f1e6040d889e.png)

experienced with 0.3-alpha

**Comment by andreas-eberle** [comment]
Can you give us some screenshots for the single problems?

**Comment by krichter722** [comment]
I figured that this is not related to using imported maps, but installing the german full version in `playonlinux` 4.2.10-2ubuntu1 with `wine` 1.19 on Ubuntu 16.10.

**Comment by andreas-eberle** [comment]
OK, this is the issue that the different versions of the settlers game provide different graphics files. In order to be compatible with all of them, we need to introduce a mechanism selecting the correct indexes depending on the detected version.

**Comment by andreas-eberle** [comment]
Closing this in favor of #573 where we want to coordinate the fix for this.
