### ISSUE TITLE
Eclipse does not compile

### ISSUE THREAD

**Issue by rpolzer** [jsettlers/settlers-remake#515]
I made a fork and clone from github as proposed. Building the Android software works fine using Android Studio, but Eclipse does not build the PC software:

In Eclipse, I selected in the menu
File / Import / Gradle project / clone folder selected
then the package explorer shows some parts, three of them (Android parts) having red crosses. So far it looks good.

But the menu
Project / Build all
is gray, CTRL-B shows no reaction and right clicking on jsettlers.main.swing shows no "Build".

I am using Eclipse 4.5.2 for Java on a 64 bit Debian, which is working for other Java projects.

**Comment by abledbody** [comment]
It has been my experience that Eclipse automatically builds the project all the time. The GitHub wiki may be a bit dated...

**Comment by rpolzer** [comment]
Could you please give me a hint how to proceed with Eclipse after having done the clone?

**Comment by abledbody** [comment]
As far as I know the best way to start is to import the project by creating a new java project and selecting the clone folder as the project location. It will automatically import it from there. If you intend to run it all you need to do is make a run configuration with the SwingManagedJSettlers Main class. You may need to clean the project before you can do that, but I haven't been able to get everything working on my end due to #501.

**Comment by rpolzer** [comment]
I tried this, and compiling works, but the compiled software crashes:

Exception in thread "main" java.lang.ExceptionInInitializerError
	at jsettlers.main.swing.lookandfeel.JSettlersLookAndFeel.install(JSettlersLookAndFeel.java:66)
	at jsettlers.main.swing.SwingManagedJSettlers.createJSettlersFrame(SwingManagedJSettlers.java:209)
	at jsettlers.main.swing.SwingManagedJSettlers.main(SwingManagedJSettlers.java:65)
Caused by: java.lang.NullPointerException
	at javax.swing.ImageIcon.<init>(ImageIcon.java:217)
	at jsettlers.main.swing.lookandfeel.ui.img.UiImageLoader.get(UiImageLoader.java:55)
	at jsettlers.main.swing.lookandfeel.ui.ButtonUiStone.<init>(ButtonUiStone.java:46)
	at jsettlers.main.swing.lookandfeel.factory.ButtonUiFactory.<clinit>(ButtonUiFactory.java:40)
	... 3 more

ButtonUiStone.java:46 does not find the file granit_texture1.png, which exists in the directory jsettlers.main.swing/src/main/resources/jsettlers/main/swing/lookandfeel/ui/img

**Comment by rpolzer** [comment]
I found a solution to make the game running - but I think this was not intended by the authors:

copy all image files from
(clone directory)/jsettlers.main.swing/bin/jsettlers/main/swing/lookandfeel/ui/img/
to
(clone directory)/go.graphics/bin/jsettlers/main/swing/lookandfeel/ui/img/

**Comment by abledbody** [comment]
@rpolzer I can't find the bin directories anywhere.

**Comment by rpolzer** [comment]
I did an update for my Eclipse from Mars to Neon, but that should not change anything.

I tried a second time to verify what has to be done to compile:

- fork the repository
- clone the repository, I suggest to put the cloned setllers-remake within the Eclipse workspace directory
- start Android Studio and open the cloned directory as an Android project and let it compile (if we don't do this, we will later have to copy jsettlers.graphics/src/main/resources/jsettlers/graphics/map/draw/settlerimages/movables.txt to bin/jsettlers/graphics/map/draw/settlerimages/ and also the class CommitInfo would be missing)
- start Eclipse for Java
- Eclipse: File / New / Java Project, choose settlers-remake as project name
- Eclipse: Run / Run configurations, new configuration, select the project and jsettlers.main.swing as main class
- Eclipse: Project / Properties /Java Compiler / tick Enable project specific settings / Compiler compliance level 1.8
- copy images from jsettlers.main.swing/src/main/resources/jsettlers/main/swing/lookandfeel/ui/img/ to go.graphics/build/classes/main/jsettlers/main/swing/lookandfeel/ui/img/
- then the game compiles and starts - only at the point "waiting for other player" it stops

**Comment by abledbody** [comment]
You mean like in #246?
I get the feeling that this is history repeating itself...

**Comment by rpolzer** [comment]
I don't know: I found neither the mentioned ant scripts nor the MaterialInventoryLayout.

**Comment by rpolzer** [comment]
Probably this is a new issue having the title "Game does not run".

**Comment by rpolzer** [comment]
- the game seems not to run because com.jogamp.opengl libraries are missing in the project tree
- a clean in Eclipse removes the manually copied images, so after a clean, compiling does not work any more

**Comment by andreas-eberle** [comment]
@rpolzer: Since the switch to gradle, we cannot really support Eclipse any more. None of us main developers is currently using it. We all switched to Android Studio / IntelliJ. Would it be an idea for you to try out Android Studio or IntelliJ? This would certainly save you a lot of trouble...

**Comment by rpolzer** [comment]
I tried IntelliJ - but was not able to set the run configuration. Please help.

**Comment by homoroselaps** [comment]
I can't give you IntelliJ support, but I strongly recommend Android Studio (IntelliJ specialized for Android dev). It is literally "zero manual configuration" for this project.

**Comment by rpolzer** [comment]
I have already used Android Studio for the Android app - but does Android Studio also build the PC jar file? Please give some advice.

**Comment by homoroselaps** [comment]
As for as I remember you simple start the SwingManagedJSettlers class:
![temp](https://cloud.githubusercontent.com/assets/7871498/24578777/20858628-16e8-11e7-9b94-03d13ccbca31.png)
My configuration looks like this:
![temp2](https://cloud.githubusercontent.com/assets/7871498/24578779/34caa29e-16e8-11e7-91f7-ee14ddb31723.png)

**Comment by rpolzer** [comment]
When I try to set the main class for the run configuration as described, I get the error message

Class 'jsettlers.main.swing.SwingManagedJSettlers' not found in module settlers-remake

**Comment by homoroselaps** [comment]
Please give more details. Make sure the "Use classpath of module" is set correctly. I was able to reproduce this error message by changing it - but when I simply saved it anyway, I was able to run it.
Did my first proposal work for you?

**Comment by rpolzer** [comment]
When I try to set the classpath, I get only the alternatives "<no module>" and "settlers-remake", I do not get "jsettlers.main.swing", so I can't set it as described.

**Comment by homoroselaps** [comment]
It seems to me that the project is not imported correctly if modules are missing?! But reading through this issue, I guess you have more expertise than I do. If it helps, you might ask me any question on discord: #286

**Comment by andreas-eberle** [comment]
@rpolzer: Please try the following steps one by one:
* Clone the jsettlers repository into a clean folder and make sure master is checked out
* Start IntelliJ or AndroidStudio (yes, AndroidStudio can run the normal Java code as well). 
* Click on "File" -> "Open" and select the folder you just checked out JSettlers and confirm the following dialog.
* Maybe you're asked for gradle to sync. Please do this. 

Now your project view should look like this.

![grafik](https://cloud.githubusercontent.com/assets/9267365/24619609/d5295506-189a-11e7-998c-4dbea708928b.png)

* Open the Terminal View of IntelliJ and enter `gradlew clean assemble` (or if you're on Linux: `gradle clean assemble`)
* Now open the file 'jsettlers.main.swing/src/main/java/jsettlers/main/swing/SwingManagedJSettlers.java'
* Do a right click in the editor window and select 'Run SwingManagedJSettlers.main()'.

Now the game should start. 

Did this work? If not, where exactly did it not work? Can you attach screenshots showing the problem?

**Comment by rpolzer** [comment]
Finally I got the PC version running! Thanks to all for your help!
These changes made it work:
- clone with git (using the Android Studio 'Check out project from Version Control') instead of using the zip download from github
- reopen the project file settlers-remake after the clone
- enter 'gradle clean assemble' in the terminal window
- use Android Studio instead of IntelliJ (Android Studio did the build and IntelliJ gave me some errors, see below)
Now I use Android Studio to build both the PC and the Android version.

Errors from IntelliJ:
.../settlers-remake-intellij/jsettlers.graphics/src/main/java/jsettlers/graphics/map/MapContent.java
Error:(34, 24) java: cannot find symbol
  symbol:   class CommitInfo
  location: package jsettlers.common
Error:(426, 107) java: cannot find symbol
  symbol:   variable CommitInfo
  location: class jsettlers.graphics.map.MapContent

**Comment by andreas-eberle** [comment]
@rpolzer: I'm glad it works now. I also experienced the CommitInfo problem once while I was testing the way I described you. I'll have to look into this...
