### ISSUE TITLE
Android UI improvements (progress)

### ISSUE THREAD

**Issue by Tom-Pratt** [jsettlers/settlers-remake#516]
Hi @andreas-eberle and other contributors.

I have been keen to get involved in this project for ages but not had time. But now I have some more free time and have had a go at improving the Android user interface.

https://www.dropbox.com/s/2qkn3ju2pirusm9/jsettlers.main.android-release.apk?dl=0

So far I haven't done anything with the actual game play. But focused on breaking up the Android UI structure a little. In the current version, the JSettlersActivity does a lot of the work. I have broken the JSettlersActivity responsibilities into several main things:

- MainActivity, this navigates through several menu fragments to be able to configure and launch a new game.
- GameActivity, this shows a loading fragment while the game loads followed by a map fragment for gameplay.
- GameService, all of the important running game objects are held in an Android service. This means that, all the screens can be rotated freely and they just bind back to the GameService. The game can run in the background with the main app minimised or closed, you can use other apps or lock your phone screen and the game will continue. You can reopen the app and continue gameplay until the game is actually quitted.

There is also a system notification when a game is running. From the notification you can resume, quit or pause the game (save isn't hooked up yet).

![screenshot_20161121-095102](https://cloud.githubusercontent.com/assets/10612949/20476882/72a05018-afd3-11e6-8150-2c18d0451a73.png)

If you close the app completely (swipe it away from the app drawer, or is killed by Android while not visible) then when you reopen the app the main menu shows that there is a game in progress with similar options to the notification

![screenshot_20161121-095114](https://cloud.githubusercontent.com/assets/10612949/20477367/8ffdf88e-afd5-11e6-8156-c78046bd5c53.png)

You can see the game running in portrait mode

![screenshot_20161121-101308](https://cloud.githubusercontent.com/assets/10612949/20476898/836f75c2-afd3-11e6-8893-bfa994b183f9.png)

It's quite basic so far in terms of features and styling but I think it could be a solid basis for work on the Android version to continue. So far you can only start a new single player game. Starting, pausing and quitting is hooked up and it uses broadcast manager to keep everything in sync when these high level game options are triggered from either the GameActivity, MainActivity or the notification.

If this all seems like a good approach then next I will take a look at the IControls/MobileControls and start on the in game menus.

Here is the code
https://github.com/Sylapse/settlers-remake/tree/enhancement_android_separate_ui

Cheers!
Tom

**Comment by andreas-eberle** [comment]
Wow! This looks great! Thanks a lot for this contribution! The Android UI needs a lot of work, but you're definitely going in the right direction! Keep up the work and don't hesitate if you have any questions or need something (e.g. better / other API to the game logic). I'm looking forward to your PR!

**Comment by Sylapse** [comment]
Great thanks :D 

I'll let you know if I need any help with anything. I'll try and get it closer to where the current repo is in terms of features and then that might be a good time for a PR.

**Comment by Sylapse** [comment]
Made some progress on setting up the game controls which I thought you might like to see. Can now create buildings and move soldiers.

I've made the menu using Android Bottom Sheets. Minimal styling so far while focusing and getting it easy and natural to use. I think it works well even on phone screen sizes and has lots of potential for further refinement. The three dots at the top right show pause/save/quit.

Here is the APK

https://www.bitrise.io/artifact/748102/p/8d9ba3ea5c892666313ec933df79f3a0

Couple of screenshots from phone and one on 10 inch tablet

![screenshot_20161125-095500](https://cloud.githubusercontent.com/assets/10612949/20619571/8a884882-b2f5-11e6-8efe-52710c035d24.png)


![screenshot_20161125-094654](https://cloud.githubusercontent.com/assets/10612949/20619486/217514b0-b2f5-11e6-9185-ced05f725999.jpg)


![screenshot_2016-11-25-09-48-53](https://cloud.githubusercontent.com/assets/10612949/20619488/24d30fd6-b2f5-11e6-8f6c-bc5f9d22e08a.jpg)

**Comment by andreas-eberle** [comment]
@Sylapse: How is it going? Are you making good progress?

**Comment by Sylapse** [comment]
Hi @andreas-eberle, I haven't worked on this since my last post as I have been doing some updates to my main app during december. That's mostly finished now though so looking forward to doing some more on Settlers. 

There's a couple more things I think it would be good to get in place before I make a PR. The main thing will be handling selection of buildings/settlers and showing the menu related to the selection.

I'll aim to get it ready and tidied up for a PR as soon as possible 👍🏻

**Comment by andreas-eberle** [comment]
Cool! I'm looking forward to it!

**Comment by Sylapse** [comment]
Some more progress on in game menus. The selected building menus for Normal and Occupied type buildings are both working

![screenshot_20170113-133617](https://cloud.githubusercontent.com/assets/10612949/21930399/255215c0-d996-11e6-8929-988f5b0ee81f.jpg)



![screenshot_20170113-132022](https://cloud.githubusercontent.com/assets/10612949/21930092/7697b978-d994-11e6-9a75-a542a368ec63.jpg)
