### ISSUE TITLE
Can't run the Swing version from Android Studio

### ISSUE THREAD

**Issue by Sylapse** [jsettlers/settlers-remake#517]
@andreas-eberle  I'm using Android Studio and followed the instructions in the Setting up IntelliJ IDEA wiki page.

But when I try and run the game I get these errors. Any idea on how to get this going?

Thanks

![screenshot 2016-11-25 15 49 21](https://cloud.githubusercontent.com/assets/10612949/20628707/d68b02ce-b327-11e6-8786-e063c990fdca.png)

**Comment by andreas-eberle** [comment]
I experienced that too. It seems that Android Studio is not packaging the resources correctly / at all. For now, the only way is to use IntelliJ for the Swing version or directly use the gradle task.
