### ISSUE TITLE
Missing Animations

### ISSUE THREAD

**Issue by andreas-eberle** [jsettlers/settlers-remake#52]
In the following I will list movables with missing animations. I will extend the list with further findings. Feel free to post you additions.

@michaelzangl: can you write a wiki post, explaining how animations can be found and added?

* PIG_FARMER: 
  * Taking
  * Dropping
  * WATER
  * CROP
  * PIG
* SMITH
  * Taking 
  * Dropping
* BEARERS
  * Taking/Dropping 
    * GOLD_ORE
    * COAL

**Comment by stumpdk** [comment]
Many working movables have a small moment when they change state, in which they turn into ordinary carrieres, until the new state. For example just after a saw workers dropping state.

**Comment by andreas-eberle** [comment]
Can you list the movables with this issue? Is this still the case with the current code (I made an improvement to reduce this times...)

**Comment by adamjryan** [comment]
I think my submission [Worker drop animation correction] addresses this.

**Comment by justangel** [comment]
I started to work on the transfer of all available animations here https://github.com/jsettlers/settlers-remake/pull/69 has found and corrected several errors, typos. I try to scrutinize the issue, but no one is immune from typos =) so the comments in the code that might raise questions, I hope my English is not too bad =)

**Comment by andreas-eberle** [comment]
Should be finished now with the merge of #69.
