### ISSUE TITLE
If automatic locale search fails show english as default instead nothing

### ISSUE THREAD

**Issue by Fantu** [jsettlers/settlers-remake#53]
I did some test of build from master, I saw that automatically search locales, it loaded partial italian I did but don't show english for strings missed (for this probably I can found a workaround with transifex)
Another bigger problem if when not found rispective locales where don't show all strings, I think is good use english as default if not found locale.

**Comment by andreas-eberle** [comment]
@Fantu: your right. I reopen the ticket. My fault.
