### ISSUE TITLE
Update Developer's Guide?

### ISSUE THREAD

**Issue by agp89** [jsettlers/settlers-remake#530]
I just wanted to get started following the [delevolpers guide](https://github.com/jsettlers/settlers-remake/wiki/Developer's%20Guide).

It seems to me that the instructions for building with eclipse are outdated as there are no eclipse projects in the repo.

**Comment by andreas-eberle** [comment]
Thanks for the hint. I updated the guidelines. At the moment we cannot support Eclipse any more. We suggest using IntelliJ and/or Android Studio.
