### ISSUE TITLE
Mixed Translations (Alpha v0.3)

### ISSUE THREAD

**Issue by agp89** [jsettlers/settlers-remake#531]
I have german and english text mixed up. 

![mixedtranslation](https://cloud.githubusercontent.com/assets/6398661/21752171/25ad897a-d5d4-11e6-9be4-f8274412e32e.JPG)

When i start JSettlers from cmd it shows the following:
`Warning: Could not load LocaleSuffix [locale=de_DE, useCountry=true]. Falling back to next file.`

Same behaviour on Win10 and Ubuntu 16.04 LTS

If you need any more information just let me know.

**Comment by andreas-eberle** [comment]
I guess you want to see only the German localisation, correct?

**Comment by agp89** [comment]
Yes i would expect it to be either just english or just german.

**Comment by andreas-eberle** [comment]
Well, actually the mixing up is by design. Whenever the localization of a string in the desired language cannot be found, the english text is used for it. So this shows us we have to add these localizations to the localization file. Thanks for reporting this.
