### ISSUE TITLE
ESelectionType enum defaults to BUILDING even if nothing is selected

### ISSUE THREAD

**Issue by Sylapse** [jsettlers/settlers-remake#533]
Might be good to add NONE and let this be the default item. Otherwise when a selection event fires then its a case of checking the type and if its BUILDING also check if there are more than zero selection items in the set.

**Comment by michaelzangl** [comment]
We ususally do it the other way: check if there are any items selected and then do the right action.

**Comment by Sylapse** [comment]
Ah yeah I thought this would lead to lots of double checks but having used it in a few places as you described its not a problem
