### ISSUE TITLE
Can't get game to start

### ISSUE THREAD

**Issue by xjohnson21** [jsettlers/settlers-remake#55]
Windows 8.1
java version "1.8.0_45"
Java(TM) SE Runtime Environment (build 1.8.0_45-b14)
Java HotSpot(TM) Client VM (build 25.45-b02, mixed mode)

I downloaded 'JSettlers_v0.1.1-alpha.zip' and 'JSettlers_v0.1.1-alpha.tar.bz2'
I  unzipped them into the same folder on my desktop 'C:\Users\xjohnson21\Desktop\Settlers'
I edited config.prp to say 'settlers-folder=C:\BlueByte\S3AmazonenDemo' This is where the game file is installed

I can't get JSettlers.jar to do anything.

Things I've tried:

Editing the Environment Variables for 'Java' and 'Path'

I'm not very good at this stuff so I don't know what else I can do

**Comment by andreas-eberle** [comment]
Please change the settlers-folder path in the config.prp file to use slashes instead of backslashes (/ instead of \). 

If this doesn't help, try to start the game from the command line. To do this, start the command line switch to the folder with the JSettlers.jar file in it (by using cd) and execute

`java -jar JSettlers.jar --console-output`

What is the result you get?

Best regards,
Andreas

**Comment by xjohnson21** [comment]
I tried the variations with the slashes 'settlers-folder=C:/BlueByte/S3AmazonenDemo' with the same result

I tried to start from the command line and got a "file could not run" error

Again I don't know much about Java or things like this

After some Googling I created a .bat file to launch the .jar file
@echo off
title y
start java -jar "C:\Users\xjohnson21\Desktop\Settlers\JSettlers.jar" %1

That gave me this message

![settlerserror](https://cloud.githubusercontent.com/assets/12120792/7352113/a9caf234-ecd7-11e4-8d5c-65dfcb30abb3.png)

**Comment by xjohnson21** [comment]
I think this is a problem on my end. I'm going to check back at later time to see how you progress.

I'm really excited about this project, Settlers 3 was my favorite game ever!

**Comment by andreas-eberle** [comment]
Hi @xjohnson21,

did you try the newest release? With the newest release, you should not create a config.pp / delete the existing one and directly start the game. A dialog should then pop up and ask you to select the folder of the original Settlers III installation. Does this work?
