### ISSUE TITLE
Installation/Opening App on Android

### ISSUE THREAD

**Issue by jbergande** [jsettlers/settlers-remake#559]
After I followed the installation steps and started the app it asked me where the Gfx and Snd folders are located. I am not able to choose the folder where those are stored, because the button on the upper right corner of the display which says "use this folder" does not react. What shall I   ##do?

Thanks for your help in advance!

**Comment by andreas-eberle** [comment]
@jbergande: Can you try the newer Android version from PR #532? It will soon be the new version of the game. You should be able to download it from here: https://www.dropbox.com/s/845i08yrzyuwgo5/jsettlers.main.android-release.apk?dl=0

**Comment by andreas-eberle** [comment]
@jbergande: Have you tried the newer version? You can now take the version from the [master nightly builds](https://github.com/jsettlers/settlers-nightlies/blob/gh-pages/master/2017-05-27_12-10-13__1f462d5/DedicatedJSettlersServer.jar).

**Comment by jbergande** [comment]
Thank you so much for your help. I also managed to make the old version work. Now I’ll try the new One.

**Comment by andreas-eberle** [comment]
What did you do to get the older version to run? What was the problem? Maybe it can help others having the same problem...

I'm closing this issue then.
