### ISSUE TITLE
Selecting an Open Source License

### ISSUE THREAD

**Issue by andreas-eberle** [jsettlers/settlers-remake#56]
Currently our settlers-remake has no open source license yet. After having a look at the pros and cons of some licenses, @michaelzangl and I propose the MIT License. 

@stumpdk @adamjryan @justangel: You already contributed to this project, so we want to ask you if that's ok for you, so that we can set the license. Can you please post your opinion in this ticket?

**Comment by daviddawson** [comment]
:+1:

**Comment by justangel** [comment]
ok

**Comment by adamjryan** [comment]
That's fine with me.

**Comment by stumpdk** [comment]
It's perfectly fine with me.

**Comment by michaelzangl** [comment]
I added a MIT license note to all java source files (and some properties).
