### ISSUE TITLE
Wrong images shown for soldiers occupying a tower

### ISSUE THREAD

**Issue by ziarrek** [jsettlers/settlers-remake#565]
As seen in a small tower:
![tower_occupying_images](https://cloud.githubusercontent.com/assets/4028673/25773051/b5e58852-326e-11e7-9437-22bf67ddaa88.png)

The tower menu shows wrong images for the types of soldiers occupying the tower.
Tested (map 2Hours, Swing UI built and running on Ubuntu):
- level 1 swordsman shows as level 1 archer
- level 1 archer shows as level 2 pikeman
- level 3 swordsman shows as level 3 archer

**Comment by andreas-eberle** [comment]
I'm closing this in favor of #573 which targets to fix the underlying problem. @ziarrek: Thanks for reporting.
