### ISSUE TITLE
Danish locale naming dk_DK instead of da_DK

### ISSUE THREAD

**Issue by andreas-eberle** [jsettlers/settlers-remake#58]
@stumpdk: You named the danish locale file "labels_dk_DK.properties". However, in the list of [supported locales of JAVA 8](http://www.oracle.com/technetwork/java/javase/java8locales-2095355.html), the danish locale is specified as da_DK. 

What is the exact locale of your system? Would it work for you to change the file nameing to "labels_da_DK.properties"?

**Comment by Fantu** [comment]
Or probably is better only "da" for support any danish in each country they are...
