### ISSUE TITLE
App doesn't show building information after a while into the game

### ISSUE THREAD

**Issue by andreas-eberle** [jsettlers/settlers-remake#589]
The building information usually shown when selecting a building wasn't shown any more after a while into the game. No exception was in the logcat.

**Comment by andreas-eberle** [comment]
@Tom-Pratt: Do you have an idea what could be causing this?

**Comment by Tom-Pratt** [comment]
Weird. If it happens again, check the log for warnings instead of errors and see if there's anything about trying to update the UI from a background thread. I've seen the menu go blank during development for this reason. Seems weird that it would happen part way into a game though.

**Comment by Tom-Pratt** [comment]
Ah I just spotted the problem in [this commit](https://github.com/jsettlers/settlers-remake/pull/588/commits/d38a8103a7acf5a0fcbe07e2757003147582fe4b)

The selection listener is hooked up in `afterViews()` but is removed in `onStop()`.

Move adding the listener to `onStart()`

**Comment by andreas-eberle** [comment]
@Tom-Pratt: Thanks for the research. I'll test it.

**Comment by andreas-eberle** [comment]
@Tom-Pratt: Thanks for the hint. I tested it and it seams to work.
