### ISSUE TITLE
Settlers graphics walking off into eternity.

### ISSUE THREAD

**Issue by Zervox** [jsettlers/settlers-remake#6]
I see sometimes soldiers and normal settlers just starting to walk endlessly out of the map, this usually only happens in the beginning starting a map.

**Comment by andreas-eberle** [comment]
With which map did you experience that? Can you tell me exactly how to reproduce it?

**Comment by andreas-eberle** [comment]
I was able to reproduce this on the map "Nice Map". However, on "Mountain Lake", it seems to work. Furthermore on "Nice Map" buildings aren't finished. I will investigate that.
