### ISSUE TITLE
Winery is not being built

### ISSUE THREAD

**Issue by namelessjames** [jsettlers/settlers-remake#62]
Currently, a winery is not being built. Maybe even the ground is not being paved correctly? Tried several maps, not working for me. Console-output following (if there is any usable).

![untitled-1](https://cloud.githubusercontent.com/assets/858474/7372287/339490d0-edc6-11e4-941b-679c01f4a0a4.jpg)

**Comment by andreas-eberle** [comment]
The winery hasn't been implemented yet... however, it's already in the menu... the temples and the storage building are also missing. => I mark this as improvement to add the missing building.

**Comment by namelessjames** [comment]
Alright, sorry then. In general: is it alright to mark those missing things as issue?

**Comment by andreas-eberle** [comment]
Well, that's a good question for a project with a lot of missing features... I guess it's ok to report the missing buildings, so we can focus on implementing them. But I wouldn't create 200 issues for missing features at once, as this kills motivation and the usage of the queue to (also) handle bugs.

**Comment by namelessjames** [comment]
Okay, yes, fair enough! Alright then! I don't want any motivation killers. As much as I would love to contribute to the code itself, unfortunately I only can play and test - no Java knowledge here. You guys do an awesome job :heart_eyes:

**Comment by andreas-eberle** [comment]
Nevertheless, many thanks for playing the game and searching bugs!

**Comment by andreas-eberle** [comment]
I started work on this in #70
