### ISSUE TITLE
.dat file contents

### ISSUE THREAD

**Issue by gollum1001** [jsettlers/settlers-remake#623]
initFromReader in AdvancedDatFileReader executes readSequencesAt six times with different positions, but readSequencesAt differs between five sequences types.
What is the sixth type ? 

Sorry for my bad english.

**Comment by andreas-eberle** [comment]
I don't get what exactly you mean. Can you explain it in more detail?

**Comment by gollum1001** [comment]
In AdvancedDatFileReader SEQUENCE_TYPE_COUNT is six, so readSequencesAt is execute six times.
readSequencesAt reads some pointers and writes them to "<seqtype>starts" (seqtype can be settler, landscape, etc.), but readSequencesAt has five if clauses, one for every <seqtype>starts. If you go to all six sequences in a hex editor, you will see another type of sequence. The first four bytes of this sequence are 0x21702 (Little Endian).
What is this sixth sequence type ?

**Comment by andreas-eberle** [comment]
@michaelzangl: I think you can answer @gollum1001's question best.

**Comment by michaelzangl** [comment]
I don't know. I have not observed any file where that sequence was not empty. It is a sequence but it always seems to have length 0.

**Comment by gollum1001** [comment]
Gold Edition: Siedler3_25.f8007e01f.dat, Siedler3_02.f8007e01f.dat, Siedler3_15.f8007e01f.dat, Siedler3_45.f8007e01f.dat, Siedler3_35.f8007e01f.dat
Amazonen Demo: Siedler3_45.f8007e01f.dat, Siedler3_15.f8007e01f.dat

**Comment by michaelzangl** [comment]
You are right. I did not test those files because I never found out what they are good for ;-).
15, 25, 45, 35 are files belonging to the different civilizations.

Each of the sections starts with `00 0c 00 00 00 00 00 00`

I can't really make much sense of the following numbers. All I can say is that it consists of 16 bit shorts, e.g.

```
0xc200 0x1500
0xb500 0x1500
0xc200 0x1500
0x0b00 0x0b00
0xffff 0xffff
0x0000 0x0000
0xc200 0x1500
0xb500 0x1500
0xc200 0x1500
0x0a00 0x0a00
0xffff 0xffff
0x0000 0x0000
0xc200 0x1500
0xb500 0x1500
0xc200 0x1500
0x0900 0x0900
0x0200 0x0003
0x0000 0x0000
0xc200 0x1500
0xb500 0x1500
0xc200 0x1500
0x0800 0x0800
0x0200 0x0002
0x0000 0x0000
0xc200 0x1500
0xb500 0x1500
0xc200 0x1500
0x0700 0x0700
0x0200 0x0001
0x0000 0x0000
0xc200 0x1500
0xb500 0x1500
0xc200 0x1500
0x0600 0x0600
0x0200 0x0000
0x0000 0x0000
0xc200 0x1500
0xb500 0x1500
0xc200 0x1500
0x0500 0x0500
0xffff 0xffff
0x0000 0x0000
0xc200 0x1500
0xb500 0x1500
0xc200 0x1500
0x0400 0x0400
0xffff 0xffff
0x0000 0x0000
0xc200 0x1500
0xb500 0x1500
0xc200 0x1500
0x0300 0x0300
0xffff 0xffff
0x0000 0x0000
0xc200 0x1500
0xb500 0x1500
0xc200 0x1500
0x0200 0x0200
0xffff 0xffff
0x0000 0x0000
0xc200 0x1500
0xb500 0x1500
0xc200 0x1500
0x0100 0x0100
0xffff 0xffff
0x0000 0x0000
0xc200 0x1500
0xb500 0x1500
0xc200 0x1500
0x0000 0x0000
0xffff 0xffff
```

**Comment by tomsoftware** [comment]
not sure if i got the point and i'm not sure if i remember correctly but the e.g. siedler3_15xxx.dat file is a animation-and-sound sequence file. So it defines the files to use, shadow to use and body + position-offset to use when drawing a animation (e.g. a worker walking around the building), frame by frame + the sounds to trigger. My memory is quiet bad, but if you need some more informatin i will try to remember :-)

My code to reading the 15-Files:

    With m_Object(objectId).sequenz(sequenzID).images(ImageID)
      .offset = offset
      f.setOffset offset
    
    
      count = f.readIntBE(4)
      f.markString (100)

      showFrames = False
    
      For i = 1 To count
        posX = f.readSignedWordBE()
        posY = f.readSignedWordBE()
        obId = f.readIntBE(2)
        obFile = f.readIntBE(2)
       
        Debug.Print "============== " & sequenzID & ": " & obId & " (" & i & "/" & count & ")=============="
      
        torsoId = f.readIntBE(2)
        torsoFile = f.readIntBE(2)
        shadowId = f.readIntBE(2)
        shadowFile = f.readIntBE(2)
        obFrame = f.readIntBE(2)
        torsoFrame = f.readIntBE(2)
        flag3 = f.readSignedWordBE()
        flag4 = f.readSignedWordBE()
      

        Debug.Print "(" & obFile & " " & obId & " " & obFrame & ") @ " & posX & "/" & posY & "  T: (" & torsoFile & " " & torsoId & " " & torsoFrame & ")  F: " & flag3 & " " & flag4 & "  S: (" & shadowFile & " " & shadowId & ")"

        
      Next i

    End With

**Comment by gollum1001** [comment]
Thank you

I don`t understand your field names.
What is obId, obFile, obFrame, flag3 and flag4 ?

**Comment by tomsoftware** [comment]
every settler object is splittet in 3 images:
- object image -> File siedler3_4.xxxx.dat
- torso image -> File siedler3_5.xxxx.dat
- shadow image  -> File siedler3_6.xxxx.dat

every image is saved in a sequence so to adress a image you need:
- obFile :  Index of the object file: e.g. Siedler3_11.f8007e01f.dat
- obID : Index of the sequence in the file
- obFrame : Frame of the sequence 

Flag3/4 are flags... i think to hide / show the gfx or play a sound .... don't knwo

**Comment by gollum1001** [comment]
Okay..., but where is the shadow frame ?

**Comment by tomsoftware** [comment]
i think it is always the same as the object or the torso frame so they don't add it twice... but that's your turn :-P
it took me awhile to figure that out and it is quite long ago for me so I'm not sure if everything's right...

**Comment by tomsoftware** [comment]
by the way see:
https://github.com/tomsoftware/sied3/blob/master/src/clGFXFile.cpp#L164

**Comment by tomsoftware** [comment]
may I ask: Why're you interested?

**Comment by gollum1001** [comment]
I am writting a little program to extract pictures from s3 dat files, so I read the JSettlers source and found that JSettlers reads six sequences but ignores one of them.

**Comment by michaelzangl** [comment]
This might be interesting to reduce our movables.txt file.

The main reason I did not dig any deeper was that I was not really interested in the game logic stuff. The goal was to get the image data.
