### ISSUE TITLE
Problems on i686 Ubuntu, Netbook EEE PC 901

### ISSUE THREAD

**Issue by PayDay1** [jsettlers/settlers-remake#624]
When I start the jar file using java, I get this output:
https://hastebin.com/cevejamika.pl

After loading a map, I get this output and the game crashes.
https://hastebin.com/bayepovize.nginx

The device is an **EEE PC 901**.
**OS:** Ubuntu 16.10 yakkety
**Kernel:** i686 Linux 4.8.0-53-generic
**CPU:** Intel Atom CPU N270 @ 1.6GHz
**GPU:** Mesa DRI Intel(R) 945GME x86/MMX/SSE2
**RAM:** 2GB

**glxinfo**:
https://hastebin.com/dicepigugo.py

Experienced using build **c3add121**.

**Comment by gollum1001** [comment]
"Nicht genügend Hauptspeicher verfügbar" means that your RAM is full.
Try to close Firefox and similar memory consuming Applications and start JSettlers.

**Comment by PayDay1** [comment]
It also happens when starting with 230MB/2000MB RAM usage. Are 2GB of RAM not enough?

**Comment by gollum1001** [comment]
I can`t start JSettlers in a Linux VM with  2GB RAM, but it works with 4 GB.

Yes, 2 GB for JSettlers are enough, but not if these 2 GB include the kernel and all system processes.

But this may work:

1. change to `CTRL+ALT+F1`
2. enter your username and password
3. stop lightdm (Ubuntus **d**isplay **m**anager; this will release very much RAM) with `sudo service lightdm stop`
4. start JSettlers with a new X11 instance with `startx java -jar YourJSettlers.jar` (eventually you have to type `sudo` before startx of it).
5. restart lightdm after this with `sudo service lightdm start`
6. change to `CTRL+ALT+F1` again
7. exit the shell
8. change to `CTRL+ALT+F7`

**Comment by andreas-eberle** [comment]
@gollum1001: So this can be closed?

**Comment by gollum1001** [comment]
I think so

**Comment by PayDay1** [comment]
@gollum1001 I tried to run X11 without a window manager like you explained, but `startx java -jar YourJSettlers.jar` results in `unknown command line option "-jar"´.
Then I tried ´startx; java -jar YourJSettlers.jar´, but then XFCE4 just launches again.

**Comment by andreas-eberle** [comment]
@PayDay1: Sorry, I thought @gollum1001 started this issue...

**Comment by gollum1001** [comment]
> startx java -jar YourJSettlers.jar

I`m sorry I have not tested this step.

In my VM this worked:
1. Install jarwrapper (, it allows starting of jars like shell scripts) `sudo apt-get install jarwrapper`
2. Make YourJSettlers.jar executable `sudo chmod u+x YourJSettlers.jar
3. Start JSettlers in `CTRL+ALT+F1` (lightdm should be stopped) with  `startx ./YourJSettlers.jar`

**Comment by PayDay1** [comment]
Thank you, that worked.
Unfortunately there is still not enough RAM, so it seems like I won't be playing JSettlers on that little machine.
The RAM usage was at ~140MB/2000MB.

But I still have my Android Smartphone. :)
