### ISSUE TITLE
Soldier finding empty tower: range too short

### ISSUE THREAD

**Issue by benhandschuh** [jsettlers/settlers-remake#633]

**Comment by DerKrawallkeks** [comment]
You should add a short description of the issue, makes it a lot easier to understand the problem.
You mean the range of a solider to look for an empty tower is too small?

(I don't even think it is too small)

**Comment by benhandschuh** [comment]
Yep. I think the range is to short. But maybe its just a thing i must get used to.

**Comment by Simulant87** [comment]
Compared to the original the soldier request range should be extended by a factor of 2,5
