### ISSUE TITLE
Resource distribution to mines not set correctly

### ISSUE THREAD

**Issue by benhandschuh** [jsettlers/settlers-remake#634]
Food resource distribution to mines not set correctly in the beginning (one mine type gets all: iron mine). If set, but just one mine is built, that mine gets all food (no matter what type).

**Comment by andreas-eberle** [comment]
I don't understand what you mean exactly. Can you explain it a bit more?

**Comment by stumpdk** [comment]
The default distribution of meat, bread and fish is set so that iron mines get all.

**Comment by stumpdk** [comment]
Fixed in the nightly builds (8ab28fbd)
