### ISSUE TITLE
wrong icon for wine bottles!

### ISSUE THREAD

**Issue by benhandschuh** [jsettlers/settlers-remake#637]
<img width="230" alt="bildschirmfoto 2017-07-09 um 19 46 01" src="https://user-images.githubusercontent.com/16464811/27996299-7c0943fa-64df-11e7-8778-5484b11dbd0e.png">

**Comment by benhandschuh** [comment]
On the second last row on the right side, that supposed to be the wine icon.

**Comment by michaelzangl** [comment]
This is a problem with the demo/full version/gold edition icon indexes. They have changed. I don't remember which set is currently supported for the wine bottle icon.

**Comment by andreas-eberle** [comment]
These bugs are bundled in #573
