### ISSUE TITLE
Missing classes in alpha v0.4.0 ?

### ISSUE THREAD

**Issue by Gordakan** [jsettlers/settlers-remake#647]
Hey !

I have cloned the repository and checked out v0.4.0-alpha, but it seems like there are some missing classes. 
It seems to be mainly due to a missing package.

> Error:(52, 36) java: package jsettlers.graphics.ui.layout does not exist

I would like to run it with swing but I'm unable to compile it. I have been through the developer's guide and the wiki. 

Did I miss something ?

Cheers

**Comment by michaelzangl** [comment]
Those classes are generated. How do you try to compile it?

**Comment by Gordakan** [comment]
I applied what I read under  **Run using Swing**
 https://github.com/jsettlers/settlers-remake/wiki/Setting-up-IntelliJ-IDEA-(Linux,-WIndows,-OSX)

**Comment by andreas-eberle** [comment]
Which IDE are you using? There seems to be a bit trouble with IntelliJ IDEA. Try Android Studio and try compiling via the command line (e.g. via gradlew clean release)

**Comment by Gordakan** [comment]
Using IntellJ. After a few tries I finally got past the issue. I'm just not used to gradle :/

**Comment by andreas-eberle** [comment]
It is often best to do a gradle release the first time you try to run the project. We will have to improve our gradle scripts to get rid of these problems in the future. However, as this will be an ongoing task, I'll close this issue. Please reopen if you strugle again.
