### ISSUE TITLE
Setting a material distribution to zero for all buildings causes bugs

### ISSUE THREAD

**Issue by tom-pratt** [jsettlers/settlers-remake#677]
Noticed a weird bug while developing the materials distribution menu on Android, and then was able to recreate the bug in the swing version.

If you set the distribution of any material to zero to all buildings for that material, then after that new buildings will not be built.

*Steps to reproduce*
- start a game
- go to distributions menu
- choose any material and set the distribution to all buildings to zero
- try and build a new building. the building will not be built

**Comment by rpolzer** [comment]
solved - see pull request
