### ISSUE TITLE
Cannot find JSettlers.jar in Alpha 0.4.0 release zip file

### ISSUE THREAD

**Issue by meepeek** [jsettlers/settlers-remake#685]
Where did you place the file ?

**Comment by andreas-eberle** [comment]
Did you download the Android release bundle? I just tested it and the JSettlers.jar is included.

**Comment by meepeek** [comment]
Nope. I wanna run in linux

**Comment by andreas-eberle** [comment]
What does the package contain when you download this here: https://github.com/jsettlers/settlers-remake/releases/download/v0.4.0-alpha/JSettlers_v0.4.0-alpha.zip

**Comment by meepeek** [comment]
I can play it now. Thanks. I think I confuse with the source.

It works nice and smoothly on deepin, debian based. Only Roman can be played on the Alpha, is that correct ?

**Comment by andreas-eberle** [comment]
Yes, only Romans can be played. Please see our discord for more discussions (https://discord.gg/2hVV4u6).
