### ISSUE TITLE
Website is not working

### ISSUE THREAD

**Issue by InFerYes** [jsettlers/settlers-remake#695]
Would you like some help setting it up?

**Comment by DerKrawallkeks** [comment]
Hey, I think there is already an issue opened (#684). Mmh I hope this project isn't falling asleep, since the issues aren't being assigned to topics anymore:) sadly I also can't code

**Comment by michaelzangl** [comment]
Closing this as duplicate.

The original project initiators are no longer at university and do not have as much free time as they once had.
