### ISSUE TITLE
Movable animations with inverse order needed

### ISSUE THREAD

**Issue by andreas-eberle** [jsettlers/settlers-remake#71]
Some movables, for example the farmer, do not have dedicated animations for taking and dropping materials. Therefore the take animation needs to be played in the inverse order to be used as drop animation.

**Comment by andreas-eberle** [comment]
Further discussions showed a bigger change is needed here. I'm closing this in favor of issue #72.

**Comment by justangel** [comment]
ok, thanks a lot
