### ISSUE TITLE
Rework take / drop animation cycle

### ISSUE THREAD

**Issue by andreas-eberle** [jsettlers/settlers-remake#72]
### Current situation:
Movables can "take" or "drop" a material. During this process either the "TAKE" or "DROP" animation is played.

### Problem with current solution
When taking or dropping something, the movable should do the following steps: 
* "bend down"
* change the material type accordingly and 
* "raise up" again.

However, the current solution can only display a TAKE animaition or a DROP animation. To simulate the correct behavior, the current solution for building movables is to first do a DROP, change the material and then do a TAKE animation. However, in between these animations, the movable is shown with NO_ACTION, meaning standing upright. Furthermore, often there is no dedicated animation for "raise up", but it is simply the "bend down" animation played in the inverse order.

### Suggested solution / Steps to go
(as disccussed with @michaelzangl )

* The current actions "TAKE" and "DROP" need to be changed to "BEND_DOWN" and "RAISE_UP", as this is really what we need. Furthermore, the UI should implement any RAISE_UP animation as the inverse animation of the according "BEND_DOWN" animation. 
* The movable logic needs to be adapted to support a take/drop operation, which does the following:
  * play BEND_DOWN animation
  * update the material accordingly and place/take the material on/from the map
  * play RAISE_UP animation
* The building scripts and the movables.txt file need to be adapted.

I will open a branch for this change and start with the part of the logic soon.

**Comment by justangel** [comment]
glad to hear it, because really it is necessary!
about animation is not always just DROP, sometimes there is only TAKE, as can be seen from this commit
https://github.com/justangel/settlers-remake/commit/8aa1a10202669a13d6cd92690064e03a2700f9a0
LUMBERJACK don't have DROP animation, i checked it recently... maybe when I finish studying all the files of the original game, then I find additional animation, but have not seen yet

**Comment by andreas-eberle** [comment]
I opened the branch [enhancement_take_drop_animation](https://github.com/jsettlers/settlers-remake/tree/enhancement_take_drop_animation).
