### ISSUE TITLE
DatFileViewer: Add index of image in sequence

### ISSUE THREAD

**Issue by andreas-eberle** [jsettlers/settlers-remake#720]
In the GUI files (e.g. file index 14), it is very hard to find the indexes of the gui elements as there is only one very long sequence. It would be good to have the files indexed like the sequences are.

**Comment by andreas-eberle** [comment]
@nptr: Since you developed the new DatFileViewer, would this be something you can contribute?

**Comment by nptr** [comment]
i'll have a look at it!
