### ISSUE TITLE
Ship shadows seem bugged

### ISSUE THREAD

**Issue by andreas-eberle** [jsettlers/settlers-remake#736]
E.g. the shadow hides the dock. 

![grafik](https://user-images.githubusercontent.com/9267365/41872198-6ba2b7d4-78c1-11e8-8185-1743801915c0.png)

and for some directions, the wrong shadows seem to be used. E.g.
![grafik](https://user-images.githubusercontent.com/9267365/41872297-b9643ace-78c1-11e8-9c05-bb1284810870.png)

@rpolzer: Can you have a look?

**Comment by rpolzer** [comment]
@andreas-eberle: does it make sense to push these changes to the pull request
"push ships when building a new one"
or would it be better to make a new pull request?

**Comment by rpolzer** [comment]
@andreas-eberle: I just saw you branch make-ships-leave-dock, so I'll make a new pull request.

**Comment by andreas-eberle** [comment]
@rpolzer: It's always better to make a new PR for stuff that does not really belong together.

**Comment by rpolzer** [comment]
solved with pull request Dock shadow #737
