### ISSUE TITLE
build.ant is broken

### ISSUE THREAD

**Issue by justangel** [jsettlers/settlers-remake#78]
[javac] G:\JSettlers\jsettlers.logic\src\jsettlers\logic\buildings\others\TempleBuilding.java:75: error: cannot access IStackSizeSupplier
    [javac]             super.getGrid().getMapObjectsManager().addWineBowl(super.getDoor(), getWineStack());
    [javac]                                                   ^
    [javac]   class file for IStackSizeSupplier not found
    [javac] 1 error

BUILD FAILED
G:\JSettlers\build.ant:13: The following error occurred while executing this line:
G:\JSettlers\jsettlers.tests\build\build.ant:119: The following error occurred while executing this line:
G:\JSettlers\jsettlers.logic\build\build.ant:82: Compile failed; see the compiler error output for details.

**Comment by andreas-eberle** [comment]
I cannot reproduce this. Furthermore, Travis is fine. Maybe you're missing the file on your system? 
@michaelzangl: Can you reproduce this?

**Comment by justangel** [comment]
Hmm, strange, OK, I'll take more research, if will not work, I'll try through Travis

**Comment by justangel** [comment]
downloaded the repository to a different folder, launched build.ant and everything is OK

p.s.
compare directories, much different, strange, nothing there to edit, for that, I have another copy in another folder
