### ISSUE TITLE
The folder of the original Settlers installation must be requested on first startup

### ISSUE THREAD

**Issue by andreas-eberle** [jsettlers/settlers-remake#8]
Instead of letting the user configure the folder in the config file, we should open a dialog on first startup or whenever the settlers files cannot be found. This dialog should allow you to select the folder and save this to the configuration file.

**Comment by andreasb242** [comment]
I may help implementing it, but not today ;-)
There is another issue, the Original folder is called SND.

	public String[] getSndFolders() {
		return getFolders("Snd");
	}

This is not working on Linux, because usually the Fielesystem is case sensitive...

**Comment by andreas-eberle** [comment]
Hi @andreasb242,

feel free to develop it and send me a Pull Request. I thought of a simple folder select dialog. Nothing fancy.

Regarding the other bug, I opened a seperate ticket #11. In the future, simply open a new ticket ;)

**Comment by Fantu** [comment]
Probably the folder name have different case-sentive in different installation.
I installed S3 with wine from old original cdroms and the folder was Snd and Gfx.
A solution probably is to add an exist condition that try both case.

**Comment by adamjryan** [comment]
Given the demo is freely available on the web why not just bundle it with this and then it will be in a known location and the config can be bypassed.

**Comment by Fantu** [comment]
The settlers 3 license should be checked, redistribution is high probably prohibited and probably also use of resource of demo is limited.
