### ISSUE TITLE
Android seems to not localize correctly

### ISSUE THREAD

**Issue by andreas-eberle** [jsettlers/settlers-remake#99]
Via a comment on the project website (see http://www.settlers-android-clone.com/jsettlers-is-open-source-first-alpha-released/#comment-15381), I've been told there would be localization issues on Android. Can anyone confirm this?

**Comment by justangel** [comment]
I confirm the problem of localization (all in German)
checked on the device: WEXLER-TAB-7iS (Android 4.1.1)

**Comment by michaelzangl** [comment]
Only de/en localization is available at the moment. The locale is always the locale of your device, English if it is not available.
